### ISSUE TITLE
Can't load a statically linked elf binary.

### ISSUE THREAD

**Issue by ianamason** [cea-sec/miasm#1030]
Hard to know what the problem is, due to the lack of documentation.
But a statically linked 'hello world'  binary causes  
`miasm.analysis.binary.Container.from_string` to throw: an exception.
```Traceback (most recent call last):
  File "./s0.py", line 21, in <module>
    cont = Container.from_string(content)
  File "/usr/local/lib/python3.5/dist-packages/miasm/analysis/binary.py", line 46, in from_string
    return container_type(data, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/miasm/analysis/binary.py", line 95, in __init__
    self.parse(data, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/miasm/analysis/binary.py", line 214, in parse
    fill_loc_db_with_symbols(self._executable, self.loc_db, addr)
  File "/usr/local/lib/python3.5/dist-packages/miasm/jitter/loader/elf.py", line 79, in fill_loc_db_with_symbols
    if not rel.sym or rel.offset == 0:
  File "/usr/local/lib/python3.5/dist-packages/miasm/loader/elf_init.py", line 107, in get_sym
    return self.parent.linksection.symtab[self.cstr.info >> 32].name
AttributeError: 'NullSection' object has no attribute 'symtab'

```

Am I expecting too much from the framework? 
Am I not using it correctly?    For completeness, the `s0.py` script is:

```
import sys
from miasm.analysis.binary import Container
from miasm.analysis.machine import Machine

if len(sys.argv) != 2:
    print('Usage:\n\t{} <binary>'.format(sys.argv[0]))
    exit(1)

fpath = sys.argv[1]

with open(fpath, 'rb') as fp:
    content = fp.read()

print('{} is {} bytes'.format(fpath, len(content)))

cont = Container.from_string(content)

bin_stream = cont.bin_stream
entry_point = cont.entry_point

machine = Machine(cont.arch)
mdis = machine.dis_engine(bin_stream)
blocks = mdis.dis_multiblock(cont.entry_point)
open("cfg.dot", "w").write(blocks.dot())

```
Also for completeness I am running in a fresh vagrant Ubuntu 16.04 box, with python  3.5.2

**Comment by serpilliere** [comment]
Hi @ianamason !
Thank you for the feedback: It's clearly a bug in the elf loader. You can try with the following patch:
```diff
diff --git a/miasm/loader/elf_init.py b/miasm/loader/elf_init.py
index 36c4cfafc..786d030b8 100644
--- a/miasm/loader/elf_init.py
+++ b/miasm/loader/elf_init.py
@@ -104,6 +104,8 @@ class WRel64(StructWrapper):
     wrapped._fields.append(("type", "u32"))
 
     def get_sym(self):
+        if not hasattr(self.parent.linksection, 'symtab'):
+            return None
         return self.parent.linksection.symtab[self.cstr.info >> 32].name
 
     def get_type(self):

```

> Am I expecting too much from the framework?

I am afraid I don't understand: can you elaborate?

**Comment by ianamason** [comment]
Thanks for the fix @serpilliere!
