### ISSUE TITLE
Print AssignBlock error

### ISSUE THREAD

**Issue by J4ckKn1ght** [cea-sec/miasm#1033]
When I try to print an AssignBlock or print step of Symbolic Execution Engine. It make an error about sort between Expr

> Traceback (most recent call last):
Instr PUSH       RBP
  File "Test.py", line 10, in <module>
Assignblk:
    sb.run_block_at(ircfg, address, step=True)
  File "Local\Programs\Python\Python36\lib\site-packages\miasm\ir\symbexec.py", line 1055, in run_block_at
    addr = self.eval_updt_irblock(irblock, step=step)
  File "Local\Programs\Python\Python36\lib\site-packages\miasm\ir\symbexec.py", line 1036, in eval_updt_irblock
    print(assignblk)
  File "Local\Programs\Python\Python36\lib\site-packages\miasm\ir\ir.py", line 259, in __str__
    for dst, src in sorted(viewitems(self._assigns)):
TypeError: '<' not supported between instances of 'ExprMem' and 'ExprId'

Maybe it is a python3 problem?

**Comment by serpilliere** [comment]
Your analyze seems correct.

**Comment by serpilliere** [comment]
Can you try with the PR #1045 ?
I added the p3 ordering test (`__eq__` and `__ne__` was already there, so implementing `__lt__` seems to do the trick)
