### ISSUE TITLE
Test_all.py errors

### ISSUE THREAD

**Issue by JessicaFavin** [cea-sec/miasm#1091]
Hello,

I'm getting some errors on test_all.py after a fresh install on these 4 tests :

- ir/translators/smt2.py
- arch/x86/unit/mn_div.py llvm
- arch/x86/qemu/testqemu64.py test-x86_64 test_mul expected_x86_64/test_mul.exp --jitter llvm
- ir/translators/z3_ir.py

The errors from mn_div.py and testqemu64.py seem to be cause by a segmentation fault (displayed when I ran the test individualy).
The other two are errors raised by z3 (which I installed with pip).

The error messages displayed at the end of test_all.py are :
```
Result: 572/576 pass

ERROR smt2.py

Traceback (most recent call last):
  File "smt2.py", line 52, in <module>
    s.add(e_z3 != smt2_z3)
  File "/usr/lib/python3.7/site-packages/z3/z3.py", line 949, in __ne__
    a, b = _coerce_exprs(self, other)
  File "/usr/lib/python3.7/site-packages/z3/z3.py", line 1096, in _coerce_exprs
    b = s.cast(b)
  File "/usr/lib/python3.7/site-packages/z3/z3.py", line 1391, in cast
    _z3_assert(is_expr(val), "True, False or Z3 Boolean expression expected. Received %s" % val)
  File "/usr/lib/python3.7/site-packages/z3/z3.py", line 98, in _z3_assert
    raise Z3Exception(msg)
z3.z3types.Z3Exception: True, False or Z3 Boolean expression expected. Received [If(And(Extract(7,
                0,
                Extract(15, 0, Extract(31, 0, a) + b)*c) <<
        (LShR(d, 5 & 8 - 1) | d << 8 - (5 & 8 - 1)) !=
        0,
        True),
    a + 100,
    22) ==
 If(And(e +
        (1 ^
         Extract(0, 0, Extract(7, 0, a)) ^
         Extract(1, 1, Extract(7, 0, a)) ^
         Extract(2, 2, Extract(7, 0, a)) ^
         Extract(3, 3, Extract(7, 0, a)) ^
         Extract(4, 4, Extract(7, 0, a)) ^
         Extract(5, 5, Extract(7, 0, a)) ^
         Extract(6, 6, Extract(7, 0, a)) ^
         Extract(7, 7, Extract(7, 0, a))) !=
        0,
        True),
    Concat(mem64[a*a + 7],
           Concat(mem64[a*a + 6],
                  Concat(mem64[a*a + 5],
                         Concat(mem64[a*a + 4],
                                Concat(mem64[a*a + 3],
                                       Concat(mem64[a*a + 2],
                                        Concat(mem64[a*a + 1],
                                        mem64[a*a]))))))),
    Concat(mem64[a + 7],
           Concat(mem64[a + 6],
                  Concat(mem64[a + 5],
                         Concat(mem64[a + 4],
                                Concat(mem64[a + 3],
                                       Concat(mem64[a + 2],
                                        Concat(mem64[a + 1],
                                        mem64[a]))))))))]
                                        
ERROR x86/unit/mn_div.py llvm
''

ERROR testqemu64.py test-x86_64 test_mul expected_x86_64/test_mul.exp --jitter llvm
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[WARNING]: Create dummy entry for 'xxx.dll'
[DEBUG]: new imp __gmon_start__ 6402040
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp putchar 6402072
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp puts 6402080
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp sigaction 6402088
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp exp 6402096
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp atan 6402104
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp __stack_chk_fail 6402112
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp memset 6402120
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp sincos 6402128
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp log 6402136
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp fmod 6402144
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp acos 6402152
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp __libc_start_main 6402160
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp _setjmp 6402168
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp sigemptyset 6402176
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp tan 6402192
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp atan2 6402200
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp __printf_chk 6402208
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp __longjmp_chk 6402216
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp asin 6402224
[DEBUG]: warning adding .dll to modulename
[DEBUG]: xxx.dll
[DEBUG]: new imp sqrt 6402232

ERROR z3_ir.py
Traceback (most recent call last):
  File "z3_ir.py", line 103, in <module>
    [(0xdeadbeef, 2), (0xdeadbeef + 3, 0)])
  File "z3_ir.py", line 27, in check_interp
    l = interp.as_list()
AttributeError: 'ArrayRef' object has no attribute 'as_list'
```

Are these error common or did I miss a step during build or install ?

Thanks

**Comment by serpilliere** [comment]
Yes, kind of:
#994

That's why we are using an old llvm in regression tests (see our travis setup)
@aguinet is trying to fix the bug in the llvm wrappers here: numba/llvmlite#495

**Comment by JessicaFavin** [comment]
Ah great. Thanks !
Should I use an older llvm version for the GreHack workshop or will it be fine this way ?
