### ISSUE TITLE
Use example/disasm/full.py script happen error

### ISSUE THREAD

**Issue by chago** [cea-sec/miasm#1178]
command option:
```
-g -p -x -y -e -j
```

error:
```
Traceback (most recent call last):
  File "full.py", line 332, in <module>
    ircfg = simplifier.simplify(ircfg_a, head)
  File full.py", line 317, in simplify
    ssa = self.do_simplify_loop(ssa, head)
  File "miasm/analysis/simplifier.py", line 307, in do_simplify_loop
    modified = self.do_simplify(ssa, head)
  File "full.py", line 313, in do_simplify
    modified |= load_from_int(ssa.graph, bs, is_addr_ro_variable)
  File "miasm/analysis/data_flow.py", line 1238, in load_from_int
    mems = get_memlookup(src, bs, is_addr_ro_variable)
  File "miasm/analysis/data_flow.py", line 1210, in get_memlookup
    return memlookup_visit(expr, bs, is_addr_ro_variable)
  File "miasm/analysis/data_flow.py", line 1205, in memlookup_visit
    lambda expr: memlookup_test(expr, bs, is_addr_ro_variable, result))
TypeError: visit() takes exactly 2 arguments (3 given)

# -->
def memlookup_visit(expr, bs, is_addr_ro_variable):
    result = set()
    expr.visit(lambda expr: expr,
               lambda expr: memlookup_test(expr, bs, is_addr_ro_variable, result))
    return result
```

**Comment by serpilliere** [comment]
Hi @chago 
Thank you for the bug report
#1181 should fix the issue
