### ISSUE TITLE
The CFG is too big, simplifier expression with recursive so that  spend unpredictable time

### ISSUE THREAD

**Issue by chago** [cea-sec/miasm#1197]
args: -g -p -x -y -e -j

The full.py script running with a couple of hours, finally I stopped the script manually, i think that python's recursive efficiency is too low...
 How to solve this problem?

```
Traceback (most recent call last):
  File "...", line 328, in <module>
    ircfg = simplifier.simplify(ircfg_a, head)
  File "...", line 314, in simplify
    ssa = self.do_simplify_loop(ssa, head)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/simplifier.py", line 307, in do_simplify_loop
    modified = self.do_simplify(ssa, head)
  File "...", line 308, in do_simplify
    modified = super(CustomIRCFGSimplifierSSA, self).do_simplify(ssa, head)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/simplifier.py", line 297, in do_simplify
    return super(IRCFGSimplifierSSA, self).simplify(ssa, head)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/simplifier.py", line 32, in ret_func
    modified = func(self, ircfg, head)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/simplifier.py", line 70, in simplify
    modified |= simplify_pass(ircfg, head)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/simplifier.py", line 32, in ret_func
    modified = func(self, ircfg, head)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/simplifier.py", line 254, in do_propagate_expr
    modified = self.propag_expr.propagate(ssa, head)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/data_flow.py", line 881, in propagate
    new_src = src.replace_expr(replace)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 633, in replace_expr
    return visitor.visit(self)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 359, in visit
    arg = self.visit(expr.arg, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 359, in visit
    arg = self.visit(expr.arg, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 359, in visit
    arg = self.visit(expr.arg, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 359, in visit
    arg = self.visit(expr.arg, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 359, in visit
    arg = self.visit(expr.arg, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 365, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 359, in visit
    arg = self.visit(expr.arg, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 359, in visit
    arg = self.visit(expr.arg, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 359, in visit
    arg = self.visit(expr.arg, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 359, in visit
    arg = self.visit(expr.arg, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 359, in visit
    arg = self.visit(expr.arg, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 395, in visit_inner
    ret = super(ExprVisitorCallbackTopToBottom, self).visit(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 362, in visit
    args = [self.visit(arg, *args, **kwargs) for arg in expr.args]
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 387, in visit
    ret = self.visit_inner(expr, *args, **kwargs)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 392, in visit_inner
    ret = self.callback(expr)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 632, in <lambda>
    visitor = ExprVisitorCallbackTopToBottom(lambda expr:replace(expr))
KeyboardInterrupt
```

![image](https://user-images.githubusercontent.com/2239471/80179472-36db0980-8633-11ea-97e5-878c41a86305.png)

**Comment by serpilliere** [comment]
Hi @chago !
Can you try using #1168 ?

**Comment by chago** [comment]
No results have been produced after running for 5 hours. Is it possible to optimize this function, such as multi-threading or optimization algorithm?

```
INFO : ok
INFO : import machine...
INFO : ok
INFO : func ok 0000000003d640d0 (0)
INFO : generate graph file
[0x3D640D0 0x3D69D50]
INFO : generate intervals
INFO : total lines 0
INFO : generating IR and IR analysis
INFO : generating IR... 3d640d0
INFO : Print blocks (without analyse)
INFO : Gen Graph... 3d640d0
INFO : Print blocks (with analyse)
Traceback (most recent call last):
  File "full.py", line 312, in <module>
    ircfg = simplifier.simplify(ircfg_a, head)
  File "full.py", line 301, in simplify
    ssa = self.do_simplify_loop(ssa, head)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/simplifier.py", line 312, in do_simplify_loop
    modified = self.do_simplify(ssa, head)
  File "full.py", line 295, in do_simplify
    modified = super(CustomIRCFGSimplifierSSA, self).do_simplify(ssa, head)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/simplifier.py", line 302, in do_simplify
    return super(IRCFGSimplifierSSA, self).simplify(ssa, head)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/simplifier.py", line 32, in ret_func
    modified = func(self, ircfg, head)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/simplifier.py", line 70, in simplify
    modified |= simplify_pass(ircfg, head)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/simplifier.py", line 32, in ret_func
    modified = func(self, ircfg, head)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/simplifier.py", line 294, in do_dead_simp_ssa
    modified = self.deadremoval(ssa.graph)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/data_flow.py", line 391, in __call__
    ret = self.do_dead_removal(ircfg)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/data_flow.py", line 375, in do_dead_removal
    defuse = DiGraphDefUse(reaching_defs, deref_mem=True)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/data_flow.py", line 149, in __init__
    deref_mem=deref_mem)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/data_flow.py", line 164, in _compute_def_use
    deref_mem=deref_mem)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/data_flow.py", line 178, in _compute_def_use_block
    AssignblkNode(block.loc_key, index, lval))
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/data_flow.py", line 194, in add_data_edge
    self.add_uniq_labeled_edge(src, dst, ATTR_DEP)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/analysis/data_flow.py", line 188, in add_uniq_labeled_edge
    self.add_uniq_edge(src, dst)
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/core/graph.py", line 101, in add_uniq_edge
    dst not in self._nodes_succ[src]):
  File "/Users/admin/venv/shusui/lib/python2.7/site-packages/miasm/expression/expression.py", line 197, in __eq__
    def __eq__(self, other):
KeyboardInterrupt
```

**Comment by serpilliere** [comment]
Hi @chago !
Maybe we have one of the simplification method which has a deplorable complexity.
Is it possible to share the sample? Or just the function of the sample?

You will be able to use multithreading with your current script, but using the future rust version of miasm (but it's not public yet :cry: )

**Comment by chago** [comment]
Ok,this is a function of cropping, offset is 0, arm64 architecture:

[aarch64_func_offset_0.bin.zip](https://github.com/cea-sec/miasm/files/4543918/aarch64_func_offset_0.bin.zip)

**Comment by serpilliere** [comment]
Thank you @chago

**Comment by chago** [comment]
Thank you @serpilliere

**Comment by serpilliere** [comment]
In fact, we have multi threading, but in the Rust version of Miasm.
The Miasm's core has been re implemented in Rust, and we have python bindings to expose the very same API than today.
This way, you can implement algorithm in python, but if you want a fast or multithread one, you can implement it in Rust.
The problem is it's not ready, so we didn't published it yet :cry:

**Comment by chago** [comment]
I guess the reason is that this expression is very large. Disassembling this expression uses multiple layers of recursion. In Python, deep recursion is very slow

<img width="680" alt="截屏2020-05-22 下午2 20 22" src="https://user-images.githubusercontent.com/2239471/82638008-84e62b80-9c38-11ea-85b3-19fbf662a9ae.png">

<img width="578" alt="截屏2020-05-22 下午2 20 32" src="https://user-images.githubusercontent.com/2239471/82646761-b9adaf00-9c47-11ea-8104-4cdbcda55347.png">


<img width="1335" alt="截屏2020-05-22 下午2 21 05" src="https://user-images.githubusercontent.com/2239471/82637894-58caaa80-9c38-11ea-8eb8-e092a0debf99.png">

And finally reported an error at this position

![image](https://user-images.githubusercontent.com/2239471/82646939-ff6a7780-9c47-11ea-85fc-42b62bc9abe2.png)

**Comment by serpilliere** [comment]
Oh, it seems your case trigger an error in the expression propagation :cry: 
with such a graph, it will be very hard to track down..

**Comment by nofiv** [comment]
I've got probably the same problem, however the smallest ircfg I found has got 109 blocks which is much smaller, do you want me to share? My code:

```
ssa = simp.ircfg_to_ssa(self.ircfg, LocKey(0))
simp.do_propagate_expressions(ssa, LocKey(0))  # stuck
```
