### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte on mac with mach-o binaries 

### ISSUE THREAD

**Issue by dvcrn** [cea-sec/miasm#1263]
Hi, 

I discovered miasm and tried to load up a few samples. OS is MacOS, the binaries are in Mach-O format. 

The 3 binaries I tried to loadup gave me
```
Traceback (most recent call last):
  File "sample1.py", line 16, in <module>
    c = Container.from_stream(dat)
  File "/Users/d/src/reverseflow/miasm/venv/lib/python3.7/site-packages/miasm/analysis/binary.py", line 74, in from_stream
    return Container.from_string(stream.read(), *args, **kwargs)
  File "/Users/d/src/reverseflow/miasm/venv/bin/../lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte
```

Code
```
c = Container.from_stream(open("/Applications/Path/To/My/Binary"))
```

I'm wondering, 
- is miasm compatible with mach-o binaries? 
- Are other steps needed to load binaries due to the codec errors? 
- Can I use something like lief to load the binary into the container/machine memory? 

In triton I would do:

```
    binary = lief.parse("/Path/To/Binary")
    phdrs = binary.segments
    for phdr in phdrs:
        size = phdr.size
        vaddr = phdr.virtual_address
        vaddr += MEMORY_OFFSET

        print("[+] Loading binary %s -> %s" % (hex(vaddr), hex(vaddr+size)))
        Triton.setConcreteMemoryAreaValue(vaddr, phdr.content)
```

**Comment by serpilliere** [comment]
Hi!
Nop, we don't have a Mach-o loader for now.
By the way, maybe you want to open the file using:
```python
open("/Applications/Path/To/My/Binary", 'rb')
```
instead of:
```python
open("/Applications/Path/To/My/Binary")
```

Anyway, you might want to use a very bad trick to open your mach-o: for a given section, you may calculate the difference between the file offset and the section address, and open it using:
```python
Container.from_stream(fdesc, addr=base_address)
```
It allow miasm to open the file and give a base address to simulate the file/virtual address of a section

**Comment by dvcrn** [comment]
Ah I see, that's what I feared. Let me try the offset hack then. 

How about using something like lief that supports mach-o as I mentioned above to load the binary and then feed it into miasm? Would that be feasible?

**Comment by serpilliere** [comment]
Yes! Maybe you can use lief or any other mach-o parser to allow Miasm work on such a file.

**Comment by dvcrn** [comment]
I have tried to use `lief` to load the binary into miasm. It's working good so far but I noticed a little problem related to the base address when using jitter

```python
machine = Machine('x86_64')
mn = machine.mn
jitter = machine.jitter(jit_type='python')
jitter.init_stack()

phdrs = binary.segments
for phdr in phdrs:
    size = phdr.size
    vaddr = phdr.virtual_address

    vaddr += MEMORY_OFFSET

    print("[+] Loading binary %s -> %s" % (hex(vaddr), hex(vaddr+size)))
    b = bytes(bytearray(phdr.content))
    jitter.vm.add_memory_page(vaddr, PAGE_READ | PAGE_WRITE, b)
```

I am using a `MEMORY_OFFSET` since the concrete memory dump I have got taken from a binary that got loaded with `MEMORY_OFFSET`. 

When running:
Instruction:
```
0x102521459 48 b8 00 00 00 02 01 00 00 00 movabs rax, 0x102000000
```
Where 0x102000000 is the MEMORY_OFFSET

In miasm the instruction resulted in:
```
102521459 MOV        RAX, 0x0
```
which matches with my disassembler because it doesn't account for the offset of where the binary got loaded. 

Can I change the base load addr of jitter to handle this?

**Comment by serpilliere** [comment]
Hi @dvcrn 
Maybe you are facing a relocation mechanism: I don't have many information from your question, but in *your* dump, the binary may have been loaded by a real loader right? So the binary has its relocations fixed.
But maybe the information you got from lief are the raw datas. You have to extract the relocations information from lief, in the mach-o and fix them, don't you think?

**Comment by dvcrn** [comment]
That makes sense, let me see if I can fix it when loading the binary with lief
