### ISSUE TITLE
z3 translation crashes

### ISSUE THREAD

**Issue by mrphrazer** [cea-sec/miasm#127]
Translation of a basic block to z3 expressions crashes with following error:

```
Extract(63, 0, Extract(63, 0, RSP) + 8) == RSP
RBP ==
Concat(mem64[Extract(63, 0, RSP) + 8 + 7],
       Concat(mem64[Extract(63, 0, RSP) + 8 + 6],
              Concat(mem64[Extract(63, 0, RSP) + 8 + 5],
                     Concat(mem64[Extract(63, 0, RSP) +
                              8 +
                              4],
                            Concat(mem64[Extract(63, 0, RSP) +
                                     8 +
                                     3],
                                   Concat(mem64[Extract(63,
                                        0,
                                        RSP) +
                                        8 +
                                        2],
                                        Concat(mem64[Extract(63,
                                        0,
                                        RSP) +
                                        8 +
                                        1],
                                        mem64[Extract(63,
                                        0,
                                        RSP) +
                                        8])))))))
RSP == RBP
Extract(31, 0, RDI) ==
Concat(mem64[RBP + 18446744073709551612 + 3],
       Concat(mem64[RBP + 18446744073709551612 + 2],
              Concat(mem64[RBP + 18446744073709551612 + 1],
                     mem64[RBP + 18446744073709551612])))
If(Concat(mem64[RBP + 18446744073709551612 + 3],
          Concat(mem64[RBP + 18446744073709551612 + 2],
                 Concat(mem64[RBP + 18446744073709551612 + 1],
                        mem64[RBP + 18446744073709551612]))) +
   1337 !=
   0,
   0,
   1) ==
zf
Extract(31,
        31,
        Concat(mem64[RBP + 18446744073709551612 + 3],
               Concat(mem64[RBP + 18446744073709551612 + 2],
                      Concat(mem64[RBP +
                               18446744073709551612 +
                               1],
                             mem64[RBP +
                               18446744073709551612]))) +
        1337) ==
nf
WARNING: invalid function application for =, sort mismatch on argument at position 2, expected (_ BitVec 32) but given (_ BitVec 1)
WARNING: (declare-fun = ((_ BitVec 32) (_ BitVec 32)) Bool) applied to: 
(bvand (bvadd (concat #27 #36) bv[1337:32]) bv[255:32]) of sort (_ BitVec 32)
pf of sort (_ BitVec 1)

Traceback (most recent call last):
  File "z3-translate.py", line 40, in <module>
    print translator.Translator.to_language('z3').from_expr(e)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/ir/translators/z3_ir.py", line 193, in from_expr
    ret = super(TranslatorZ3, cls).from_expr(expr)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/ir/translators/translator.py", line 109, in from_expr
    return handler(expr)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/ir/translators/z3_ir.py", line 174, in from_ExprAff
    return (src == dst)
  File "/usr/lib/python2.7/dist-packages/z3.py", line 786, in __eq__
    return BoolRef(Z3_mk_eq(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
  File "/usr/lib/python2.7/dist-packages/z3core.py", line 1361, in Z3_mk_eq
    raise Z3Exception(lib().Z3_get_error_msg_ex(a0, err))
z3types.Z3Exception: type error
```
Assembly code:
```
0x400546: PUSH       RBP
0x400547: MOV        RBP, RSP
0x40054a: MOV        DWORD PTR [RBP+0xFFFFFFFFFFFFFFFC], EDI
0x40054d: CMP        DWORD PTR [RBP+0xFFFFFFFFFFFFFFFC], 0x539
0x400554: JNZ        loc_000000000040055D:0x0040055d
```

This code triggers the crash:
```
ib = ira.get_bloc(addr)
for ir in ib.irs:
	for e in ir:
		print translator.Translator.to_language('z3').from_expr(e)
```

**Comment by serpilliere** [comment]
Hi

There is a bug in the Z3 translator:
If an expression is an operator and this operator has only one argument, the translator simply drop the operator.

```python
    @classmethod
    def from_ExprOp(cls, expr):
        args = map(cls.from_expr, expr.args)
        res = args[0]
        for arg in args[1:]:
            if expr.op in cls.trivial_ops:
                res = eval("res %s arg" % expr.op)
            elif expr.op == ">>":
                res = z3.LShR(res, arg)
            elif expr.op == "a>>":
                res = res >> arg
            elif expr.op == "a<<":
                res = res << arg
            else:
                raise NotImplementedError("Unsupported OP yet: %s" % expr.op)
        return res
```

In your code, one of the expression is:
```
pf = (parity ((@32[(RBP+0xFFFFFFFFFFFFFFFC)]+(- 0x539))&0xFF))
```
Here `parity` is an operator with only one argument, so it generates:
```
pf =  ((@32[(RBP+0xFFFFFFFFFFFFFFFC)]+(- 0x539))&0xFF)
```
And the size of `pf` (1 bit) differs from the source (8 bit here)

**Comment by fmonjalet** [comment]
Thanks @mrphrazer for reporting and @serpilliere for finding the bug. I'll fix the unary-dropping-bug and support parity ASAP!
Are there any other unary operator that are commonly used?

**Comment by serpilliere** [comment]
If you look at the code in `translators/C.py`:
```python
...
        if len(expr.args) == 1:
            if expr.op == 'parity':
                return "parity(%s&0x%x)" % (cls.from_expr(expr.args[0]),
                                            size2mask(expr.args[0].size))
            elif expr.op in ['bsr', 'bsf']:
                return "x86_%s(%s, 0x%x)" % (expr.op,
                                             cls.from_expr(expr.args[0]),
                                             expr.args[0].size)
            elif expr.op == '!':
                return "(~ %s)&0x%x" % (cls.from_expr(expr.args[0]),
                                        size2mask(expr.args[0].size))
            elif expr.op in ["hex2bcd", "bcd2hex"]:
                return "%s_%d(%s)" % (expr.op, expr.args[0].size,
                                      cls.from_expr(expr.args[0]))
            elif (expr.op.startswith("double_to_") or
                  expr.op.endswith("_to_double")   or
                  expr.op.startswith("access_")    or
                  expr.op.startswith("load_")      or
                  expr.op in ["-", "ftan", "frndint", "f2xm1",
                              "fsin", "fsqrt", "fabs", "fcos"]):
                return "%s(%s)" % (expr.op, cls.from_expr(expr.args[0]))
...
```

But only the `parity`, `bsf`, `bsr` may be sufficient (the `!` operator is not used anymore if I remember correctly). By the way, `parity` only read 8 bits (low) (operator made for x86)

Maybe it can be implemented in z3 using something like:
```
parity(x) = 1 ^ x[0:1] ^x[1:2]^...^x[7:8]
```

**Comment by fmonjalet** [comment]
PR #128 should fix the problem for parity (as well as for the '-' unary operator). I will implement the other operators in the future. What do `bsf` and `bsr` do?

**Comment by serpilliere** [comment]
No, parity is computed as follow (`vm_mngr.c`):
```C
unsigned int parity(unsigned int a)
{
#if defined(__builtin_parity)
	return __builtin_parity(a);
#else
    unsigned int tmp, cpt;

    tmp = a&0xFF;
    cpt = 1;
    while (tmp!=0){
	    cpt^=tmp&1;
	    tmp>>=1;
    }
    return cpt;
#endif
}
```

**Comment by fmonjalet** [comment]
Thank you, I will update the translator accordingly. TranslatorPython might have to be updated too. :)

**Comment by serpilliere** [comment]
Ho ho. I didn't notice the error in python as well thank you.
