### ISSUE TITLE
type get_or_create_offset_location

### ISSUE THREAD

**Issue by deadeert** [cea-sec/miasm#1290]
Hello! 

I updated miasm today and it seems that some changes make my scripts not working anymore. 
I get the following backtrace when running script given at the end. 

```
Traceback (most recent call last):
  File "dse.py", line 68, in <module>
    j.continue_run()
  File "/usr/lib/python3.8/site-packages/miasm/jitter/jitload.py", line 412, in continue_run
    return next(self.run_iterator)
  File "/usr/lib/python3.8/site-packages/miasm/jitter/jitload.py", line 380, in runiter_once
    self.pc = self.run_at(self.pc)
  File "/usr/lib/python3.8/site-packages/miasm/jitter/jitload.py", line 335, in run_at
    return self.jit.run_at(
  File "/usr/lib/python3.8/site-packages/miasm/jitter/jitcore.py", line 179, in run_at
    cur_block = self.disasm_and_jit_block(offset, cpu.vmmngr)
  File "/usr/lib/python3.8/site-packages/miasm/jitter/jitcore.py", line 142, in disasm_and_jit_block
    cur_block = self.mdis.dis_block(addr)
  File "/usr/lib/python3.8/site-packages/miasm/core/asmblock.py", line 1356, in dis_block
    current_block, _ = self._dis_block(offset)
  File "/usr/lib/python3.8/site-packages/miasm/core/asmblock.py", line 1227, in _dis_block
    loc_key = self.loc_db.get_or_create_offset_location(offset)
AttributeError: 'str' object has no attribute 'get_or_create_offset_location'
```

```
  m = Machine(ARCH)
  j = m.jitter(JITTER)
  # Map binary' LOAD segments   
  map_segments(argv[1],j)
  j.init_stack()
  # Map argument  
  j.vm.add_memory_page(0x20000,PAGE_READ|PAGE_WRITE,b'\xfd'*0x10)
  run_addr = 0x1119
  j.init_run(run_addr)
  j.add_breakpoint(0x1164,bp)
  j.continue_run()
```
It seems that there is type confusion. Maybe I missing something with the location database ? I did not create/attach any on the jitter, because it seems to be handled internally.   

Thanks you

**Comment by serpilliere** [comment]
The api on the `master` has changed.:
```python
>>> m = Machine("x86_32")
>>> help(m.jitter)
class jitter_x86_32(miasm.jitter.jitload.Jitter)
 |  jitter_x86_32(loc_db, *args, **kwargs)
 |  
 |  Main class for JIT handling
 |  
 |  Method resolution order:
 |      jitter_x86_32
 |      miasm.jitter.jitload.Jitter
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, loc_db, *args, **kwargs)

```
 
The first argument of the jitter is a `locaitondb`.

Maybe I will enforce a test of a the class of the first parameter to ensure the user can see this update ?

**Comment by serpilliere** [comment]
Note the API change will be explained in the `ChageLog` in the next release of Miasm

**Comment by deadeert** [comment]
Apologies I could get this one myself as I noticed it was the case for the DSEPathConstraint.. 
Thanks ! 

Peace
