### ISSUE TITLE
Running tests without installing

### ISSUE THREAD

**Issue by epsilon-0** [cea-sec/miasm#1303]
Currently, I am trying to upgrade our package for OpenBSD and am having some issues running the tests without first installing the package.

If I install the package all tests seem to be passing, but without installation it keeps complaining about unsupported archs

```
===>  Regression tests for py3-miasm-2.0.1.3
cd /usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/test &&  PYTHONPATH="..:../..:../../..:../../../.."  /usr/local/bin/python3.8 ./test_all.py
 TEST/ARCH x86/arch.py
 TEST/ARCH aarch64/arch.py
 TEST/ARCH msp430/arch.py
 TEST/ARCH ppc32/arch.py
 TEST/ARCH x86/sem.py gcc
 TEST/ARCH x86/unit/mn_strings.py llvm
 TEST/ARCH x86/unit/mn_strings.py python
 TEST/ARCH x86/unit/mn_stack.py llvm
 TEST/ARCH x86/unit/mn_stack.py python
 TEST/ARCH x86/unit/mn_daa.py gcc
 TEST/ARCH x86/unit/mn_das.py llvm
 TEST/ARCH x86/unit/mn_das.py python
 TEST/ARCH x86/unit/mn_int.py gcc
 TEST/ARCH x86/unit/mn_pshufb.py llvm
 TEST/ARCH x86/unit/mn_pshufb.py python
 TEST/ARCH x86/unit/mn_pmaxu.py llvm
 TEST/ARCH x86/unit/mn_pmaxu.py python
 TEST/ARCH x86/unit/mn_pminu.py gcc
 TEST/ARCH x86/unit/mn_pcmpeq.py llvm
 TEST/ARCH x86/unit/mn_pcmpeq.py python
 TEST/ARCH x86/unit/mn_punpck.py gcc
 TEST/ARCH x86/unit/mn_psrl_psll.py gcc
 TEST/ARCH x86/unit/mn_pinsr.py python
 TEST/ARCH x86/unit/mn_pinsr.py llvm
DONE msp430/arch.py 3s
 TEST/ARCH x86/unit/mn_pextr.py gcc
DONE ppc32/arch.py 5s
 TEST/ARCH x86/unit/mn_pmovmskb.py llvm
ERROR x86/unit/mn_strings.py llvm
b'Traceback (most recent call last):\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/jitter/jitload.py", line 197, in __init__\n    from miasm.jitter.arch import JitCore_x86 as jcore\nImportError: cannot import name \'JitCore_x86\' from \'miasm.jitter.arch\' (/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/jitter/arch/__init__.py)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "x86/unit/mn_strings.py", line 53, in <module>\n    [test(*sys.argv[1:])() for test in [Test_SCAS, Test_MOVS]]\n  File "x86/unit/mn_strings.py", line 53, in <listcomp>\n    [test(*sys.argv[1:])() for test in [Test_SCAS, Test_MOVS]]\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/test/arch/x86/unit/asm_test.py", line 23, in __init__\n    self.myjit = Machine(self.arch_name).jitter(self.loc_db, jitter_engine)\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/arch/x86/jit.py", line 76, in __init__\n    Jitter.__init__(self, ir_x86_32(loc_db), *args, **kwargs)\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/jitter/jitload.py", line 216, in __init__\n    raise RuntimeError(\'Unsupported jit arch: %s\' % arch_name)\nRuntimeError: Unsupported jit arch: x86\n'
 TEST/ARCH x86/unit/mn_pmovmskb.py python
ERROR x86/unit/mn_pinsr.py python
b'Traceback (most recent call last):\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/jitter/jitload.py", line 197, in __init__\n    from miasm.jitter.arch import JitCore_x86 as jcore\nImportError: cannot import name \'JitCore_x86\' from \'miasm.jitter.arch\' (/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/jitter/arch/__init__.py)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "x86/unit/mn_pinsr.py", line 27, in <module>\n    [test(*sys.argv[1:])() for test in [Test_PINSRB]]\n  File "x86/unit/mn_pinsr.py", line 27, in <listcomp>\n    [test(*sys.argv[1:])() for test in [Test_PINSRB]]\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/test/arch/x86/unit/asm_test.py", line 23, in __init__\n    self.myjit = Machine(self.arch_name).jitter(self.loc_db, jitter_engine)\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/arch/x86/jit.py", line 76, in __init__\n    Jitter.__init__(self, ir_x86_32(loc_db), *args, **kwargs)\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/jitter/jitload.py", line 216, in __init__\n    raise RuntimeError(\'Unsupported jit arch: %s\' % arch_name)\nRuntimeError: Unsupported jit arch: x86\n'
 TEST/ARCH x86/unit/mn_pushpop.py gcc
ERROR x86/unit/mn_strings.py python
b'Traceback (most recent call last):\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/jitter/jitload.py", line 197, in __init__\n    from miasm.jitter.arch import JitCore_x86 as jcore\nImportError: cannot import name \'JitCore_x86\' from \'miasm.jitter.arch\' (/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/jitter/arch/__init__.py)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "x86/unit/mn_strings.py", line 53, in <module>\n    [test(*sys.argv[1:])() for test in [Test_SCAS, Test_MOVS]]\n  File "x86/unit/mn_strings.py", line 53, in <listcomp>\n    [test(*sys.argv[1:])() for test in [Test_SCAS, Test_MOVS]]\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/test/arch/x86/unit/asm_test.py", line 23, in __init__\n    self.myjit = Machine(self.arch_name).jitter(self.loc_db, jitter_engine)\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/arch/x86/jit.py", line 76, in __init__\n    Jitter.__init__(self, ir_x86_32(loc_db), *args, **kwargs)\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/jitter/jitload.py", line 216, in __init__\n    raise RuntimeError(\'Unsupported jit arch: %s\' % arch_name)\nRuntimeError: Unsupported jit arch: x86\n'
 TEST/ARCH x86/unit/mn_cdq.py llvm
ERROR x86/unit/mn_int.py gcc
b'Traceback (most recent call last):\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/jitter/jitload.py", line 197, in __init__\n    from miasm.jitter.arch import JitCore_x86 as jcore\nImportError: cannot import name \'JitCore_x86\' from \'miasm.jitter.arch\' (/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/jitter/arch/__init__.py)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "x86/unit/mn_int.py", line 39, in <module>\n    [test(*sys.argv[1:])() for test in [Test_INT]]\n  File "x86/unit/mn_int.py", line 39, in <listcomp>\n    [test(*sys.argv[1:])() for test in [Test_INT]]\n  File "x86/unit/mn_int.py", line 27, in __init__\n    super(Test_INT, self).__init__(jitter)\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/test/arch/x86/unit/asm_test.py", line 23, in __init__\n    self.myjit = Machine(self.arch_name).jitter(self.loc_db, jitter_engine)\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/arch/x86/jit.py", line 76, in __init__\n    Jitter.__init__(self, ir_x86_32(loc_db), *args, **kwargs)\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/jitter/jitload.py", line 216, in __init__\n    raise RuntimeError(\'Unsupported jit arch: %s\' % arch_name)\nRuntimeError: Unsupported jit arch: x86\n'
 TEST/ARCH x86/unit/mn_cdq.py python
ERROR x86/unit/mn_pcmpeq.py llvm
b'Traceback (most recent call last):\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/jitter/jitload.py", line 197, in __init__\n    from miasm.jitter.arch import JitCore_x86 as jcore\nImportError: cannot import name \'JitCore_x86\' from \'miasm.jitter.arch\' (/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/jitter/arch/__init__.py)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "x86/unit/mn_pcmpeq.py", line 89, in <module>\n    [test(*sys.argv[1:])() for test in [\n  File "x86/unit/mn_pcmpeq.py", line 89, in <listcomp>\n    [test(*sys.argv[1:])() for test in [\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/test/arch/x86/unit/asm_test.py", line 23, in __init__\n    self.myjit = Machine(self.arch_name).jitter(self.loc_db, jitter_engine)\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/arch/x86/jit.py", line 76, in __init__\n    Jitter.__init__(self, ir_x86_32(loc_db), *args, **kwargs)\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/jitter/jitload.py", line 216, in __init__\n    raise RuntimeError(\'Unsupported jit arch: %s\' % arch_name)\nRuntimeError: Unsupported jit arch: x86\n'
ERROR x86/unit/mn_stack.py llvm
b'Traceback (most recent call last):\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/jitter/jitload.py", line 197, in __init__\n    from miasm.jitter.arch import JitCore_x86 as jcore\nImportError: cannot import name \'JitCore_x86\' from \'miasm.jitter.arch\' (/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/jitter/arch/__init__.py)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "x86/unit/mn_stack.py", line 63, in <module>\n    [test(*sys.argv[1:])() for test in [Test_PUSHPOP]]\n  File "x86/unit/mn_stack.py", line 63, in <listcomp>\n    [test(*sys.argv[1:])() for test in [Test_PUSHPOP]]\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/test/arch/x86/unit/asm_test.py", line 23, in __init__\n    self.myjit = Machine(self.arch_name).jitter(self.loc_db, jitter_engine)\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/arch/x86/jit.py", line 76, in __init__\n    Jitter.__init__(self, ir_x86_32(loc_db), *args, **kwargs)\n  File "/usr/obj/ports/py-miasm-2.0.1.3-python3/miasm-b8af43b26480b65d25f6fc3832884fa1df4db4d0/miasm/jitter/jitload.py", line 216, in __init__\n    raise RuntimeError(\'Unsupported jit arch: %s\' % arch_name)\nRuntimeError: Unsupported jit arch: x86\n'
 TEST/ARCH x86/unit/mn_cpuid.py llvm
 TEST/ARCH x86/unit/mn_seh.py gcc
...
...
...
```

Would love to know how to run these without needing the package to be installed :smile_cat: 
Thanks a lot,
Aisha

**Comment by serpilliere** [comment]
Hi @epsilon-0 
Miasm has some sub modules which are 'build' from C code. So you need at least to build it:
```
python setup.py build
```
If you are not root, maybe you can use:
```
python setup.py install --user
```
which will add miasm in your `.local/lib` python env.
Or you can use virtualenv as well.

Can you elaborate a bit on the conditions in which you want to run Miasm ?

**Comment by epsilon-0** [comment]
So, I was trying to update the OpenBSD package (using its packaging system), which is where the testing is done.
The OpenBSD packaging system does build the package using `python setup.py build` so that is fine.
Next it goes into the `test/` directory and tries to run the tests using `python3.8 test_all.py`, which gives the above errors.
A small workaround which allows running *some* of the tests but still a majority fail (shown above), is to run tests with setting `PYTHONPATH`
```
cd test
PYTHONPATH=".." python3.8 test_all.py
```
Am not sure what to do here :( 
If they can't be run without installing the package, saying that should be enough too, then I can make a note about running the tests manually and disable them in the packaging system.

**Comment by serpilliere** [comment]
Ok to be clear, you are not *root* on the system ?
So what about using one of the solutions I proposed ?
(the 'install --user" doesn't need root)
Or the virtual env ?

**Comment by epsilon-0** [comment]
I am able to run them using the `install --user`.
Thanks :smile_cat:
