### ISSUE TITLE
Problem when disassembling LEA

### ISSUE THREAD

**Issue by hnhyzz** [cea-sec/miasm#1304]
When I was disassembling "48 8d 14 7f", it yields
LEA        RDX, QWORD PTR [RDI * 0x2]

However, it should be LEA        RDX, QWORD PTR [RDI * 0x2 +RDI]

**Comment by serpilliere** [comment]
Sorry but here is the result I have with the current miasm:
![lea](https://user-images.githubusercontent.com/9433661/96745705-b66d4980-13c6-11eb-9264-e31cd86ef9fa.png)
It's a RDI*`3` not RDI*`2`.

**Comment by hnhyzz** [comment]
> Sorry but here is the result I have with the current miasm:
> ![lea](https://user-images.githubusercontent.com/9433661/96745705-b66d4980-13c6-11eb-9264-e31cd86ef9fa.png)
> It's a RDI*`3` not RDI*`2`.

Thanks for your reply. I also got RDI*3 when only disassemble the single instruction. But when disassembling a memory image, it produces RDI*2. I'll check where things went wrong.

BTW, I found the disassembler is unable to work with 'c5 f9 6e c6'
Another disassembler produces 'vmovd xmm0, esi'

Traceback (most recent call last):
  File "mi.py", line 5, in <module>
    print(mn_x86.dis(b'\xc5\xf9\x6e\xc6', 64))
  File "/usr/local/lib/python3.8/dist-packages/miasm/core/cpu.py", line 1279, in dis
    raise Disasm_Exception('cannot disasm at %X' % offset_o)

**Comment by serpilliere** [comment]
Hi @hnhyzz 
Yep. We don't have implemented the vmovd yet.
