### ISSUE TITLE
Error installing on Windows 10 20H2 + Python 3.9.0

### ISSUE THREAD

**Issue by evandrix** [cea-sec/miasm#1308]
```
> pip install miasm
Collecting miasm
  Using cached miasm-0.1.3.tar.gz (554 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\user\AppData\Local\Programs\Python\Python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-0kcfuno7\\miasm\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-0kcfuno7\\miasm\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-6itwegh5'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-0kcfuno7\miasm\
    Complete output (19 lines):
    building
    build with 'all'
    running egg_info
    creating C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-6itwegh5\miasm.egg-info
    writing C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-6itwegh5\miasm.egg-info\PKG-INFO
    writing dependency_links to C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-6itwegh5\miasm.egg-info\dependency_links.txt
    writing top-level names to C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-6itwegh5\miasm.egg-info\top_level.txt
    writing manifest file 'C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-6itwegh5\miasm.egg-info\SOURCES.txt'
    reading manifest file 'C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-6itwegh5\miasm.egg-info\SOURCES.txt'
    writing manifest file 'C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-6itwegh5\miasm.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-0kcfuno7\miasm\setup.py", line 288, in <module>
        buil_all()
      File "C:\Users\user\AppData\Local\Temp\pip-install-0kcfuno7\miasm\setup.py", line 241, in buil_all
        for dirname in os.listdir(build_base):
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'build'
    build all
    build
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by evandrix** [comment]
nvm, solved

**Comment by serpilliere** [comment]
Hi @evandrix !
Just for information, what was the problem here ?
(I can't see giving your logs)
