### ISSUE TITLE
AttributeError: 'LifterModelCallAarch64l' object has no attribute 'get_block'

### ISSUE THREAD

**Issue by su-vikas** [cea-sec/miasm#1354]
Hi, 

I am trying to use SymbolicExecutionEngine for an Aarch64 binary, and get the following error:

```
Traceback (most recent call last):
  File "scripts/simplify.py", line 132, in <module>
    main()
  File "scripts/simplify.py", line 111, in main
    expr = sb.run_block_at(lifter_model_call, address)
  File "/usr/local/lib/python3.9/site-packages/miasm/ir/symbexec.py", line 1058, in run_block_at
    irblock = ircfg.get_block(addr)
AttributeError: 'LifterModelCallAarch64l' object has no attribute 'get_block'
```

I am running the latest version. 

Let me know if any other information is needed to debug this problem.

**Comment by su-vikas** [comment]
Oops. I found the problem. Sorry for the trouble.
