### ISSUE TITLE
Assertion fail     assert len(heads) == 1 when trying to export to LLVM

### ISSUE THREAD

**Issue by ghost** [cea-sec/miasm#1372]
Hello, I modified the export LLVM script file to lift the code in a function and then export it. I always get the assertion failure 

```
error: Traceback (most recent call last):
  File "<string>", line 86, in <module>
  File "C:\Program Files\IDA 7.2\python\miasm\jitter\llvmconvert.py", line 1927, in from_ircfg
    assert len(heads) == 1
AssertionError

```

This is my script code:
```
from miasm.analysis.machine import Machine
from miasm.core.locationdb import LocationDB
from miasm.analysis.simplifier import IRCFGSimplifierCommon, IRCFGSimplifierSSA
from miasm.analysis.binary import Container

loc_db = LocationDB()

machine = Machine('x86_64')

lifter = machine.lifter_model_call(loc_db)
ircfg = lifter.new_ircfg()

cont = Container.from_string(
    idc.GetManyBytes(0, 0X1000000),
    loc_db
)

mdis = machine.dis_engine(cont.bin_stream, loc_db=loc_db)



def simplify_function_cfg(FuncAddr):
    for segea in Segments():
        for FuncAddress in Functions(segea, SegEnd(segea)):
            if FuncAddr == FuncAddress:
                Function = idaapi.get_func(FuncAddr)
                asmcfg = mdis.dis_multiblock(FuncAddr)
                ircfg = lifter.new_ircfg_from_asmcfg(asmcfg)

                entry_points = set([loc_db.get_offset_location(FuncAddr)])
                head = list(entry_points)[0]
                ircfg_simplifier = IRCFGSimplifierCommon(lifter)
                ircfg_simplifier.simplify(ircfg, head)
                return

simplify_function_cfg(0xDAD0)

context = LLVMContext_IRCompilation()
context.lifter = lifter

func = LLVMFunction_IRCompilation(context, name="test")
func.ret_type = llvm_ir.VoidType()
func.init_fc()

all_regs = set()
for block in viewvalues(ircfg.blocks):
    for irs in block.assignblks:
        for dst, src in viewitems(irs.get_rw(mem_read=True)):
            elem = src.union(set([dst]))
            all_regs.update(
                x for x in elem
                if x.is_id()
            )

reg2glob = {}
for var in all_regs:
    # alloca reg = global reg
    data = context.mod.globals.get(str(var), None)
    if data is None:
        data = llvm_ir.GlobalVariable(context.mod,  LLVMType.IntType(var.size), name=str(var))
    data.initializer = LLVMType.IntType(var.size)(0)
    value = func.builder.load(data)
    func.local_vars_pointers[var.name] = func.builder.alloca(llvm_ir.IntType(var.size), name=var.name)
    func.builder.store(value, func.local_vars_pointers[var.name])
    reg2glob[var] = data

# IRCFG is imported, without the final "ret void"
func.from_ircfg(ircfg, append_ret=False)

# Finish the saving of registers (temporary version to global)
for reg, glob in viewitems(reg2glob):
    value = func.builder.load(func.local_vars_pointers[reg.name])
    func.builder.store(value, glob)

# Finish the function
func.builder.ret_void()

# Get it back
open("out.ll", "w").write(str(func))

```

How can I solve this?

**Comment by serpilliere** [comment]
Hi @NickTsl 
Maybe you have a graph with multiple heads in the ir representation.
At line 86, can you add:
```python
open('out.dot', 'w').write(ircfg.dot())
```
and graph the dot file in order to check headers?

**Comment by NickTsl** [comment]
> Hi @NickTsl
> Maybe you have a graph with multiple heads in the ir representation.
> At line 86, can you add:
> 
> ```python
> open('out.dot', 'w').write(ircfg.dot())
> ```
> 
> and graph the dot file in order to check headers?

![out](https://user-images.githubusercontent.com/77312921/121107945-e0993d80-c7d6-11eb-951a-ffaa4afb85ba.png)

here is the dot file graphed

**Comment by serpilliere** [comment]
Hum, that's strange as the function obviously has only one head.
But There is something weird in your script:
the `simplify_function_cfg` set a local variable (ircfg) which seems to be different from the global one you define at the very beginning of your script.
I reproduce the but here localy, and clearly the ircfg is null as you initialized it at the very beginning of your script.

Here is my patch:
- dont create a 'dummy' ircfg as you do at line 11 (`ircfg = lifter.new_ircfg()`)
- makes the function `simplify_function_cfg` *returns* the object you want to analyze (ircfg) like:
```python

def simplify_function_cfg(FuncAddr):
    asmcfg = mdis.dis_multiblock(FuncAddr)
    ircfg = lifter.new_ircfg_from_asmcfg(asmcfg)

    entry_points = set([loc_db.get_offset_location(FuncAddr)])
    head = list(entry_points)[0]
    ircfg_simplifier = IRCFGSimplifierCommon(lifter)
    ircfg_simplifier.simplify(ircfg, head)
    return ircfg

ircfg = simplify_function_cfg(0x401000)

```

This way you are *sure* that the ircfg is ok.
Tell me if I am wrong, but you didn't dump the previous dot at line 86, but in the function `simplify_function_cfg`, right ?

**Comment by NickTsl** [comment]
> Hum, that's strange as the function obviously has only one head.
> But There is something weird in your script:
> the `simplify_function_cfg` set a local variable (ircfg) which seems to be different from the global one you define at the very beginning of your script.
> I reproduce the but here localy, and clearly the ircfg is null as you initialized it at the very beginning of your script.
> 
> Here is my patch:
> 
> * dont create a 'dummy' ircfg as you do at line 11 (`ircfg = lifter.new_ircfg()`)
> * makes the function `simplify_function_cfg` _returns_ the object you want to analyze (ircfg) like:
> 
> ```python
> def simplify_function_cfg(FuncAddr):
>     asmcfg = mdis.dis_multiblock(FuncAddr)
>     ircfg = lifter.new_ircfg_from_asmcfg(asmcfg)
> 
>     entry_points = set([loc_db.get_offset_location(FuncAddr)])
>     head = list(entry_points)[0]
>     ircfg_simplifier = IRCFGSimplifierCommon(lifter)
>     ircfg_simplifier.simplify(ircfg, head)
>     return ircfg
> 
> ircfg = simplify_function_cfg(0x401000)
> ```
> 
> This way you are _sure_ that the ircfg is ok.
> Tell me if I am wrong, but you didn't dump the previous dot at line 86, but in the function `simplify_function_cfg`, right ?

I applied the fixes and the issue of not having 1 head is gone, however I have a different error now:


```
  File "C:\Program Files\IDA 7.2\python\miasm\jitter\llvmconvert.py", line 1922, in from_ircfg
    self.gen_irblock(irblock)
  File "C:\Program Files\IDA 7.2\python\miasm\jitter\llvmconvert.py", line 1911, in gen_irblock
    instr_attrib, attributes, instr_offsets, irblock
  File "C:\Program Files\IDA 7.2\python\miasm\jitter\llvmconvert.py", line 1567, in gen_irblock
    case2dst, case_value = self.expr2cases(src)
  File "C:\Program Files\IDA 7.2\python\miasm\jitter\llvmconvert.py", line 1475, in expr2cases
    evaluated = self.add_ir(to_eval)
  File "C:\Program Files\IDA 7.2\python\miasm\jitter\llvmconvert.py", line 1226, in add_ir
    cond = self.add_ir(expr.cond)
  File "C:\Program Files\IDA 7.2\python\miasm\jitter\llvmconvert.py", line 1203, in add_ir
    raise NotImplementedError('Unknown op: %s' % op)
NotImplementedError: Unknown op: CC_S<=
```

I do not know what is causing this problem.

To answer your question, I did not dump the dot file in `simplify_function_cfg` , I dumped it at the end of the script.

**Comment by serpilliere** [comment]
Ok!
I understand the new error: 
In miasm, if you apply all simplifications rules, the code will generate 'high level operator" like the "CC_S<=", "FLAG_EQ_CMP", ...
And the llvm converter only known low level operators.
So the trick is simple here: tell miasm to "develop" high level operators into low level bit operations.
You can do this by just adding explicit simplifications rules at the beginning of your script:
```python
from miasm.expression.simplifications import expr_simp, ExpressionSimplifier
expr_simp.enable_passes(ExpressionSimplifier.PASS_HIGH_TO_EXPLICIT)
```

**Comment by NickTsl** [comment]
Hello, thank you very much for the help, I can successfully produce an LLVM IR file and assemble it into an .obj file now.  
However, the disassembly of the new code looks nothing like the original, after lifting to miasm->producing llvm file->assembling to .obj file. 

reassembled code, from out.ll:
![image](https://user-images.githubusercontent.com/77312921/121890715-a8b75c00-cce8-11eb-93c7-ef62b9004e57.png)

Is this expected?

**Comment by serpilliere** [comment]
Hi @NickTsl 
When you translate the original asm into Miasm IR, the IR represents the whole semantic of every instruction.
When you translate this into llvm, this is the same sematic. But there is no way to link the native registers to registers for the final native registers of the target architecture. So those registers will be in fact global variables generated in the final binary.
LLVM will do it's best to to this, but in this case there always will be this boiler code.

It's a bit like if you generate code for an emulator.

You will surely ask me: but hey, I *want* llvm to bind target registers to the IR registers! How can I do that?
Currently: there is no way to say that our RSP is the RSP of the target, that everything linked to the [RSP] is in fact a local stack, ...

**Comment by serpilliere** [comment]
Oh, one last word:
If you know for example that RDI and RSI are parameters of the original function you can *teach* llvm this, and if this match your calling convention, the native rdi & rsi will be used as arguments so may match the native registers

**Comment by Redhpm** [comment]
Everything works as expected
