### ISSUE TITLE
Is miasm compatible with OSX ?

### ISSUE THREAD

**Issue by dummys** [cea-sec/miasm#27]
Hello,

I try to build miasm on my osx. After installing all the depedencies I type python setup.py build and got this:

building
build with 'all'
running build
running build_py
running build_ext
building 'miasm2.jitter.arch.JitCore_x86' extension
clang -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c miasm2/jitter/vm_mngr.c -o build/temp.macosx-10.9-x86_64-2.7/miasm2/jitter/vm_mngr.o
miasm2/jitter/vm_mngr.c:230:8: warning: explicitly assigning a variable of type 'uint64_t'
      (aka 'unsigned long long') to itself [-Wself-assign]
                        ret = ret;
                        ~~~ ^ ~~~
miasm2/jitter/vm_mngr.c:306:8: warning: explicitly assigning a variable of type 'uint64_t'
      (aka 'unsigned long long') to itself [-Wself-assign]
                        src = src;
                        ~~~ ^ ~~~
2 warnings generated.
clang -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c miasm2/jitter/vm_mngr_py.c -o build/temp.macosx-10.9-x86_64-2.7/miasm2/jitter/vm_mngr_py.o
miasm2/jitter/vm_mngr_py.c:711:24: error: use of undeclared identifier '__BIG_ENDIAN'
        self->vm_mngr.sex   = __BIG_ENDIAN;
                              ^
miasm2/jitter/vm_mngr_py.c:719:24: error: use of undeclared identifier '__LITTLE_ENDIAN'
        self->vm_mngr.sex   = __LITTLE_ENDIAN;
                              ^
2 errors generated.
SystemExit("error: command 'clang' failed with exit status 1",)
build with 'notcc'
running build
running build_py
running build_ext
building 'miasm2.jitter.arch.JitCore_x86' extension
clang -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c miasm2/jitter/vm_mngr.c -o build/temp.macosx-10.9-x86_64-2.7/miasm2/jitter/vm_mngr.o
miasm2/jitter/vm_mngr.c:230:8: warning: explicitly assigning a variable of type 'uint64_t'
      (aka 'unsigned long long') to itself [-Wself-assign]
                        ret = ret;
                        ~~~ ^ ~~~
miasm2/jitter/vm_mngr.c:306:8: warning: explicitly assigning a variable of type 'uint64_t'
      (aka 'unsigned long long') to itself [-Wself-assign]
                        src = src;
                        ~~~ ^ ~~~
2 warnings generated.
clang -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c miasm2/jitter/vm_mngr_py.c -o build/temp.macosx-10.9-x86_64-2.7/miasm2/jitter/vm_mngr_py.o
miasm2/jitter/vm_mngr_py.c:711:24: error: use of undeclared identifier '__BIG_ENDIAN'
        self->vm_mngr.sex   = __BIG_ENDIAN;
                              ^
miasm2/jitter/vm_mngr_py.c:719:24: error: use of undeclared identifier '__LITTLE_ENDIAN'
        self->vm_mngr.sex   = __LITTLE_ENDIAN;
                              ^
2 errors generated.
SystemExit("error: command 'clang' failed with exit status 1",)
Traceback (most recent call last):
  File "setup.py", line 158, in <module>
    try_build()
  File "setup.py", line 147, in try_build
    buil_all()
  File "setup.py", line 106, in buil_all
    raise ValueError('Unable to build Miasm!')
ValueError: Unable to build Miasm!

**Comment by commial** [comment]
Thanks to #408 and #421, clang is now supported (`gcc` jitter uses now `cc`, aliased to `clang` on Mac). We're getting closer!

It seems that some issues regarding bundle / dylib remains (maybe related to the `-bundle` option used by  `distutils`).

As travis now support OS X builds, once the support work, it could be great to add a new target (test matrix) in the `.travis.yml`.

**Comment by dummys** [comment]
Nice, as I don't have anymore a Mac, I can't test it.

**Comment by serpilliere** [comment]
I am re opening the issue as it's not currently fixed, and we may complete it.
