### ISSUE TITLE
missing instructions movdqa

### ISSUE THREAD

**Issue by fabien-duchene** [cea-sec/miasm#391]
Traceback (most recent call last):
...
    ira.add_instr(instr)
  File "../pyimports/miasm2/ir/ir.py", line 153, in add_instr
    self.add_bloc(b, gen_pc_updt)
  File "../pyimports/miasm2/ir/ir.py", line 233, in add_bloc
    ir_bloc_cur, ir_blocs_extra = self.instr2ir(l)
  File "../pyimports/miasm2/ir/ir.py", line 135, in instr2ir
    ir_bloc_cur, ir_blocs_extra = self.get_ir(l)
  File "../pyimports/miasm2/arch/x86/sem.py", line 3510, in get_ir
    instr.name.lower()](self, instr, *args)
KeyError: 'movdqa'

**Comment by KKomarov** [comment]
Just came around. MOVDQA is here, but MOVNTDQA is missed

    from miasm.core.locationdb import LocationDB
    from miasm.arch.x86.arch import mn_x86
    mn_x86.fromstring('MOVDQA XMM1, XMM2', loc_db, 64)

**Comment by serpilliere** [comment]
Hi @KKomarov 
The first issue shows that the *semantic* of the instruction is not implemented.
(no semantic in the miasm2/arch/x86/sem.py file)
For the second isssue, you are right, the instruction is missing in the assembler / disassembler
