### ISSUE TITLE
Assertion error when popping esp

### ISSUE THREAD

**Issue by tomchop** [cea-sec/miasm#53]
I seem to be getting an assertion error when emulating `pop esp` (it's the instruction just after `ret`; all registers are in the state they are stupposed to be). Any ideas? I can share my script and binary sample if you need to.

```
RAX 0000000000000000 RBX 0000000000400000 RCX 0000000020002098 RDX 0000000000000000
RSI 0000000000401478 RDI 0000000000400000 RSP 000000000132FEF8 RBP 00000000200015F8
zf 0000000000000001 nf 0000000000000000 of 0000000000000000 cf 0000000000000000
RIP 000000002000118B
2000118B CALL       loc_00000000200013E5:0x200013e5
RAX 0000000000000000 RBX 0000000000400000 RCX 0000000020002098 RDX 0000000000000000
RSI 0000000000401478 RDI 0000000000400000 RSP 000000000132FEF4 RBP 00000000200015F8
zf 0000000000000001 nf 0000000000000000 of 0000000000000000 cf 0000000000000000
RIP 00000000200013E5
200013E5 PUSHAD     
RAX 0000000000000000 RBX 0000000000400000 RCX 0000000020002098 RDX 0000000000000000
RSI 0000000000401478 RDI 0000000000400000 RSP 000000000132FED4 RBP 00000000200015F8
zf 0000000000000001 nf 0000000000000000 of 0000000000000000 cf 0000000000000000
RIP 00000000200013E5
200013E6 CMP        DWORD PTR [EBP+0x54], 0x0
RAX 0000000000000000 RBX 0000000000400000 RCX 0000000020002098 RDX 0000000000000000
RSI 0000000000401478 RDI 0000000000400000 RSP 000000000132FED4 RBP 00000000200015F8
zf 0000000000000001 nf 0000000000000000 of 0000000000000000 cf 0000000000000000
RIP 00000000200013E6
200013EA JZ         loc_00000000200013FE:0x200013fe
RAX 0000000000000000 RBX 0000000000400000 RCX 0000000020002098 RDX 0000000000000000
RSI 0000000000401478 RDI 0000000000400000 RSP 000000000132FED4 RBP 00000000200015F8
zf 0000000000000001 nf 0000000000000000 of 0000000000000000 cf 0000000000000000
RIP 00000000200013FE
200013FE POPAD      
RAX 0000000000000000 RBX 0000000000400000 RCX 0000000020002098 RDX 0000000000000000
RSI 0000000000401478 RDI 0000000000400000 RSP 000000000132FEF4 RBP 00000000200015F8
zf 0000000000000001 nf 0000000000000000 of 0000000000000000 cf 0000000000000000
RIP 00000000200013FE
200013FF RET        
Traceback (most recent call last):
  File "sandbox.py", line 254, in <module>
    sb.run()
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 336, in run
    super(Sandbox_Win_x86_32, self).run(addr)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 122, in run
    print self.jitter.continue_run()
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitload.py", line 297, in continue_run
    return self.run_iterator.next()
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitload.py", line 272, in runiter_once
    self.pc = self.runbloc(self.pc)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitload.py", line 244, in runbloc
    return self.jit.runbloc(self.cpu, self.vm, pc)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitcore.py", line 172, in runbloc
    self.disbloc(lbl, cpu, vm)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitcore.py", line 145, in disbloc
    self.add_bloc(cur_bloc)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitcore.py", line 101, in add_bloc
    irblocs = self.ir_arch.add_bloc(b, gen_pc_updt = True)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/ir/ir.py", line 237, in add_bloc
    self.post_add_bloc(bloc, ir_blocs_all)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/ir/ir.py", line 278, in post_add_bloc
    self.merge_multi_affect(affect_list)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/ir/ir.py", line 187, in merge_multi_affect
    for r in missing_i]
  File "/usr/local/lib/python2.7/dist-packages/miasm2/expression/expression.py", line 766, in __init__
    assert(start < stop)
AssertionError
```

**Comment by commial** [comment]
The PR #54 seems to fix your issue. If not, please re-open this issue.

Thanks for your report !
