### ISSUE TITLE
arm64 emu ldr instruction has some error........

### ISSUE THREAD

**Issue by jigerd** [cea-sec/miasm#597]
when i run jit, 'ldr x25, 0x111', like this arm64 instruction
s = '\xfco\xba\xa9\xfag\x01\xa9\xf8_\x02\xa9\xf6W\x03\xa9\xf4O\x04\xa9\xfd{\x05\xa9\xfdC\x01\x91\xff\x83\x01\xd1\xe3\x07\x00\xf9\xf4\x03\x02\xaa\xf5\x03\x01\xaa\xf6\x03\x00\xaa\x1f \x03\xd5h\xc8WX\x08\x01@\xf9\xe8/\x00\xf9\xff\x17\x00\xf9\xff\x0f\x00\xf9'
 
I got this error:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<console>", line 15, in run_it
  File "/Library/Python/2.7/site-packages/miasm2/jitter/jitload.py", line 369, in continue_run
    return self.run_iterator.next()
  File "/Library/Python/2.7/site-packages/miasm2/jitter/jitload.py", line 340, in runiter_once
    self.pc = self.runbloc(self.pc)
  File "/Library/Python/2.7/site-packages/miasm2/jitter/jitload.py", line 297, in runbloc
    return self.jit.runbloc(self.cpu, pc, self.breakpoints_handler.callbacks)
  File "/Library/Python/2.7/site-packages/miasm2/jitter/jitcore.py", line 179, in runbloc
    self.disbloc(lbl, cpu.vmmngr)
  File "/Library/Python/2.7/site-packages/miasm2/jitter/jitcore.py", line 163, in disbloc
    self.add_bloc(cur_block)
  File "/Library/Python/2.7/site-packages/miasm2/jitter/jitcore.py", line 125, in add_bloc
    irblocks = self.ir_arch.add_bloc(block, gen_pc_updt = True)
  File "/Library/Python/2.7/site-packages/miasm2/ir/ir.py", line 464, in add_bloc
    ir_blocks_all, gen_pc_updt)
  File "/Library/Python/2.7/site-packages/miasm2/ir/ir.py", line 434, in add_instr_to_irblock
    assignblk, ir_blocks_extra = self.instr2ir(instr)
  File "/Library/Python/2.7/site-packages/miasm2/ir/ir.py", line 351, in instr2ir
    ir_bloc_cur, extra_assignblk = self.get_ir(l)
  File "/Library/Python/2.7/site-packages/miasm2/arch/aarch64/sem.py", line 765, in get_ir
    instr_ir, extra_ir = get_mnemo_expr(self, instr, *args)
  File "/Library/Python/2.7/site-packages/miasm2/arch/aarch64/sem.py", line 739, in get_mnemo_expr
    raise NotImplementedError('unknown mnemo %s' % instr)
NotImplementedError: unknown mnemo ADR        X25, 0x96C4C

**Comment by commial** [comment]
Hi @jigerd,

Two things here:
* I'm not able to reproduce your bugs, because its seems there is no "ADR X25, 0x..." in the bytecode you provide (I obtain the same disasm using IDA):
```
loc_0000000000000000:0x00000000
STP        X28, X27, [SP, 0xFFFFFFFFFFFFFFA0]!
STP        X26, X25, [SP, 0x10]
STP        X24, X23, [SP, 0x20]
STP        X22, X21, [SP, 0x30]
STP        X20, X19, [SP, 0x40]
STP        X29, LR, [SP, 0x50]
ADD        X29, SP, 0x50
SUB        SP, SP, 0x60
STR        X3, [SP, 0x8]
MOV        X20, X2
MOV        X21, X1
MOV        X22, X0
NOP        
LDR        X8, [PC, 0xAF90C]
LDR        X8, [X8]
STR        X8, [SP, 0x58]
STR        XZR, [SP, 0x28]
STR        XZR, [SP, 0x18]
```
* Regarding your error, it seems the semantic of `ADR` is missing (and yes it is); #598 should fix it.

Can you try with this update?

**Comment by jigerd** [comment]
@commial 

Thanks, maybe is the same error. I read the code in the "arch/aarch64/sem.py" file, find that I need lots of time to fix it,  thaks again.......
OK, I'll try this#598
