### ISSUE TITLE
is possible to emulate windows program on linux?

### ISSUE THREAD

**Issue by kismp123** [cea-sec/miasm#636]
Is possible to emulate? 
i'am trying to emulate but error :( 

root@bad:~/Desktop# python test.py -i a
[INFO]: Loading module name 'win_dll/ucrtbased.dll'
[INFO]: Loading module name 'win_dll/api-ms-win-core-sysinfo-l1-1-0.dll'
[INFO]: Loading module name 'win_dll/api-ms-win-core-debug-l1-1-0.dll'
Error: attempt to add page (0x10000000 0x10001000) overlapping page (0x10000000 0x10001000)
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    sb = Sandbox_Win_x86_32('./console.exe', options, globals())
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 449, in __init__
    Sandbox.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 55, in __init__
    cls.__init__(self, custom_methods, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 231, in __init__
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/loader/pe.py", line 496, in vm_load_pe_and_dependencies
    vm, fstream.read(), name=fname, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/loader/pe.py", line 145, in vm_load_pe
    pe_hdr, "%r: PE Header" % name)
TypeError: known page in memory

all needed DLL included inside win_dll folder.

**Comment by serpilliere** [comment]
Hi!

The problem here is that Miasm does not handle windows `API Sets` for the moment (mecanism used in recent windows). We have a patch we are testing internally, and may release it soon!

**Comment by kismp123** [comment]
I am very excited! This is my life project.
So I want to contribute to development or testing, but how can I do that?

**Comment by serpilliere** [comment]
You can test some binaries provided on the Miasm blog: [miasm.re](http://miasm.re) !

**Comment by kismp123** [comment]
Okay.

``
pe_hdr = pe.content[:hdr_len] + max(0, (min_len - hdr_len)) * "\x00"
vm.add_memory_page(pe.NThdr.ImageBase, PAGE_READ | PAGE_WRITE, pe_hdr, "%r: PE Header" % name) # Error here 
``

normally windows dll load at 0x7f??????. [ image here](https://pasteboard.co/GTG65N3.png)
but load direct image base address that inside PE "imagebase" :([load address image](https://pasteboard.co/GTG7exb.png)

so I think need the class that do management dll address.

**Comment by kismp123** [comment]
add

vm.get_all_memory() function returned memory information dictionary

the dictionary's key is memory start address. no dll names include
key, dictionary again included
```
0x130000 ['access', 'data', 'size']
0x401000 ['access', 'data', 'size']
0x1800ac000 ['access', 'data', 'size']
0xf31000 ['access', 'data', 'size']
0x10002000 ['access', 'data', 'size']
0x1800a4000 ['access', 'data', 'size']
0xf53000 ['access', 'data', 'size']
0xf52000 ['access', 'data', 'size']
0x184b000 ['access', 'data', 'size']
0x14cc000 ['access', 'data', 'size']
0x10001000 ['access', 'data', 'size']
0x180001000 ['access', 'data', 'size']
0x180073000 ['access', 'data', 'size']
0x1800ad000 ['access', 'data', 'size']
0x1800a6000 ['access', 'data', 'size']
0x180000000 ['access', 'data', 'size']
0x10000000 ['access', 'data', 'size']
```
it works manual dll loader. it seems need dll name to get functions 

add2 

how to add unknown function ? 
```
INFO]: kernel32_GetSystemTimeAsFileTime(lpSystemTimeAsFileTime=0x13ffd0) ret addr: 0x413269
[INFO]: kernel32_GetCurrentThreadId() ret addr: 0x41327e
[INFO]: kernel32_GetCurrentProcessId() ret addr: 0x41328a
Traceback (most recent call last):
  File "./test.py", line 15, in <module>
    sb.run()
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 466, in run
    super(Sandbox_Win_x86_32, self).run(addr)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/sandbox.py", line 129, in run
    self.jitter.continue_run()
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitload.py", line 369, in continue_run
    return self.run_iterator.next()
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitload.py", line 313, in runiter_once
    for res in self.breakpoints_handler.call_callbacks(self.pc, self):
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitload.py", line 115, in call_callbacks
    res = c(*args)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitload.py", line 440, in handle_lib
    raise ValueError('unknown api', hex(jitter.pc), repr(fname))
ValueError: ('unknown api', '0x71112111L', "'kernel32_QueryPerformanceCounter'")
```

**Comment by serpilliere** [comment]
I am afraid I didn't fully understand the question.
But if you to display modules:
```
>>> sb.jitter.vm
Addr               Size               Access Comment
0x130000           0x10000            RW_    Stack
0x400000           0x1000             RWX    'samples/box_upx.exe': PE Header
0x401000           0x6000             RW_    'samples/box_upx.exe': 'UPX0\x00\x00\x00\x00'
0x407000           0x1000             RW_    'samples/box_upx.exe': 'UPX1\x00\x00\x00\x00'
0x408000           0x1000             RW_    'samples/box_upx.exe': 'UPX2\x00\x00\x00\x00'
0x45180000         0x1000             RW_    'urlmon.dll': PE Header
0x45181000         0xC7000            R__    'urlmon.dll': '.text\x00\x00\x00'
0x45248000         0x2000             R__    'urlmon.dll': '.orpc\x00\x00\x00'
0x4524A000         0xC000             RW_    'urlmon.dll': '.data\x00\x00\x00'
0x45256000         0x55000            R__    'urlmon.dll': '.rsrc\x00\x00\x00'
0x452AB000         0x8000             R__    'urlmon.dll': '.reloc\x00\x00'
0x719F0000         0x1000             RW_    'ws2_32.dll': PE Header
0x719F1000         0x13000            R__    'ws2_32.dll': '.text\x00\x00\x00'
0x71A04000         0x1000             RW_    'ws2_32.dll': '.data\x00\x00\x00'
0x71A05000         0x1000             R__    'ws2_32.dll': '.rsrc\x00\x00\x00'
0x71A06000         0x1000             R__    'ws2_32.dll': '.reloc\x00\x00'
0x76BA0000         0x1000             RW_    'psapi.dll': PE Header
0x76BA1000         0x4000             R__    'psapi.dll': '.text\x00\x00\x00'
0x76BA5000         0x4000             RW_    'psapi.dll': '.data\x00\x00\x00'
0x76BA9000         0x1000             R__    'psapi.dll': '.rsrc\x00\x00\x00'
0x76BAA000         0x1000             R__    'psapi.dll': '.reloc\x00\x00'
0x774A0000         0x1000             RW_    'ole32.dll': PE Header
0x774A1000         0x120000           R__    'ole32.dll': '.text\x00\x00\x00'
0x775C1000         0x6000             R__    'ole32.dll': '.orpc\x00\x00\x00'
0x775C7000         0x7000             RW_    'ole32.dll': '.data\x00\x00\x00'
0x775CE000         0x2000             R__    'ole32.dll': '.rsrc\x00\x00\x00'
0x775D0000         0xE000             R__    'ole32.dll': '.reloc\x00\x00'
0x77DA0000         0x1000             RW_    'advapi32.dll': PE Header
0x77DA1000         0x75000            R__    'advapi32.dll': '.text\x00\x00\x00'
0x77E16000         0x5000             RW_    'advapi32.dll': '.data\x00\x00\x00'
0x77E1B000         0x2C000            R__    'advapi32.dll': '.rsrc\x00\x00\x00'
0x77E47000         0x5000             R__    'advapi32.dll': '.reloc\x00\x00'
0x7C800000         0x1000             RW_    'kernel32.dll': PE Header
0x7C801000         0x84000            R__    'kernel32.dll': '.text\x00\x00\x00'
0x7C885000         0x5000             RW_    'kernel32.dll': '.data\x00\x00\x00'
0x7C88A000         0x76000            R__    'kernel32.dll': '.rsrc\x00\x00\x00'
0x7C900000         0x6000             R__    'kernel32.dll': '.reloc\x00\x00'
0x7C910000         0x1000             RW_    'ntdll.dll': PE Header
0x7C911000         0x7D000            R__    'ntdll.dll': '.text\x00\x00\x00'
0x7C98E000         0x5000             RW_    'ntdll.dll': '.data\x00\x00\x00'
0x7C993000         0x33000            R__    'ntdll.dll': '.rsrc\x00\x00\x00'
0x7C9C6000         0x3000             R__    'ntdll.dll': '.reloc\x00\x00'
0x7E390000         0x1000             RW_    'user32.dll': PE Header
0x7E391000         0x60000            R__    'user32.dll': '.text\x00\x00\x00'
0x7E3F1000         0x2000             RW_    'user32.dll': '.data\x00\x00\x00'
0x7E3F3000         0x2B000            R__    'user32.dll': '.rsrc\x00\x00\x00'
0x7E41E000         0x3000             R__    'user32.dll': '.reloc\x00\x00'

```


Or you can get modules addresses like that:
```python
>>> sb.libs.name2off
{'urlmon.dll': 1159200768, 'iertutil.dll': 1896980480, 'gdi32.dll': 1896996864, 'ws2help.dll': 1897000960, 'kernel32.dll': 2088763392, 'msvcrt.dll': 1896976384, 'oleaut32.dll': 1896984576, 'rpcrt4.dll': 1896988672, 'advapi32.dll': 2010775552, 'ntdll.dll': 2089877504, 'ole32.dll': 2001338368, 'shlwapi.dll': 1896992768, 'ws2_32.dll': 1906245632, 'psapi.dll': 1991901184, 'user32.dll': 2117664768}
```

**Comment by kismp123** [comment]
Thank you!
