### ISSUE TITLE
"MUL RDI": (gcc) ‘uint128_t’ undeclared

### ISSUE THREAD

**Issue by Summus6** [cea-sec/miasm#706]
Hi,
I got an emulation error with **gcc jitter** with **MUL** instruction.
It seems it's using *uint128_t* cast on *RAX* and *RDI* (in our case).
I tried it with the current *master* (not patched, as it should not use 128bits registers)
This is also occuring with older versions (ie: f66e973a8c376516d6ea09743e529fe6bd0a7b68)

The code : 
```
#!/usr/bin/env python2

from miasm2.analysis.machine import Machine
from miasm2.jitter import csts

run_addr = 0x400000

FILE = "./test.bin"
with open(FILE) as f:
    code = f.read()

jitter = Machine("x86_64").jitter("gcc")
jitter.init_run(run_addr)

jitter.init_stack()
# In the case there is more 'POP' than "PUSH'
jitter.cpu.RSP -= jitter.stack_size / 2

# Register init is not required
jitter.cpu.RCX = jitter.cpu.RBX = jitter.cpu.RDX = jitter.cpu.RSI = jitter.cpu.RDI = run_addr

jitter.vm.add_memory_page(run_addr, csts.PAGE_READ | csts.PAGE_WRITE, code)
jitter.jit.log_mn = True

while True:
    jitter.continue_run(True)
```

The data : `"\x48\xF7\xE7\xcc"`
```
0:  48 f7 e7                mul    rdi
3:  cc                      int3
```

(*int3* is used to end the block and prevent warning in disassembly"

The output:
```
/tmp/tmp4eBes3.c: In function ‘block_jitblock_400000’:
/tmp/tmp4eBes3.c:31:25: error: ‘uint128_t’ undeclared (first use in this function); did you mean ‘uint32_t’?
  var_08_00 = (((((((((((uint128_t)(mycpu->RAX & 0xFFFFFFFFFFFFFFFF)) << 0) | (((uint128_t)(0x0 & 0xFFFFFFFFFFFFFFFF)) << 64))&0xffffffffffffffffffffffffffffffff)*(((((uint128_t)(mycpu->RDI & 0xFFFFFFFFFFFFFFFF)) << 0) | (((uint128_t)(0x0 & 0xFFFFFFFFFFFFFFFF)) << 64))&0xffffffffffffffffffffffffffffffff))&0xffffffffffffffffffffffffffffffff)>>64) & 0xFFFFFFFFFFFFFFFF)?0x1:0x0))&0x1;
                         ^~~~~~~~~
                         uint32_t
/tmp/tmp4eBes3.c:31:25: note: each undeclared identifier is reported only once for each function it appears in
/tmp/tmp4eBes3.c:31:127: warning: integer constant is too large for its type
 >RAX & 0xFFFFFFFFFFFFFFFF)) << 0) | (((uint128_t)(0x0 & 0xFFFFFFFFFFFFFFFF)) << 64))&0xffffffffffffffffffffffffffffffff)*(((((uint128_t)(mycpu->RDI & 0xFFFFFFFFFFFFFFFF)) << 0) | (((uint128_t)(0x0 & 0xFFFFFFFFFFFFFFFF)) << 64))&0xffffffffffffffffffffffffffffffff))&0xffffffffffffffffffffffffffffffff)>>64) & 0xFFFFFFFFFFFFFFFF)?0x1:0x0))&0x1;
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp4eBes3.c:31:270: warning: integer constant is too large for its type
 >RDI & 0xFFFFFFFFFFFFFFFF)) << 0) | (((uint128_t)(0x0 & 0xFFFFFFFFFFFFFFFF)) << 64))&0xffffffffffffffffffffffffffffffff))&0xffffffffffffffffffffffffffffffff)>>64) & 0xFFFFFFFFFFFFFFFF)?0x1:0x0))&0x1;
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp4eBes3.c:31:307: warning: integer constant is too large for its type
 ((uint128_t)(0x0 & 0xFFFFFFFFFFFFFFFF)) << 64))&0xffffffffffffffffffffffffffffffff))&0xffffffffffffffffffffffffffffffff)>>64) & 0xFFFFFFFFFFFFFFFF)?0x1:0x0))&0x1;
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp4eBes3.c:32:127: warning: integer constant is too large for its type
 >RAX & 0xFFFFFFFFFFFFFFFF)) << 0) | (((uint128_t)(0x0 & 0xFFFFFFFFFFFFFFFF)) << 64))&0xffffffffffffffffffffffffffffffff)*(((((uint128_t)(mycpu->RDI & 0xFFFFFFFFFFFFFFFF)) << 0) | (((uint128_t)(0x0 & 0xFFFFFFFFFFFFFFFF)) << 64))&0xffffffffffffffffffffffffffffffff))&0xffffffffffffffffffffffffffffffff)>>64) & 0xFFFFFFFFFFFFFFFF)?0x1:0x0))&0x1;
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp4eBes3.c:32:270: warning: integer constant is too large for its type
 >RDI & 0xFFFFFFFFFFFFFFFF)) << 0) | (((uint128_t)(0x0 & 0xFFFFFFFFFFFFFFFF)) << 64))&0xffffffffffffffffffffffffffffffff))&0xffffffffffffffffffffffffffffffff)>>64) & 0xFFFFFFFFFFFFFFFF)?0x1:0x0))&0x1;
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp4eBes3.c:32:307: warning: integer constant is too large for its type
 ((uint128_t)(0x0 & 0xFFFFFFFFFFFFFFFF)) << 64))&0xffffffffffffffffffffffffffffffff))&0xffffffffffffffffffffffffffffffff)>>64) & 0xFFFFFFFFFFFFFFFF)?0x1:0x0))&0x1;
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp4eBes3.c:33:126: warning: integer constant is too large for its type
 >RAX & 0xFFFFFFFFFFFFFFFF)) << 0) | (((uint128_t)(0x0 & 0xFFFFFFFFFFFFFFFF)) << 64))&0xffffffffffffffffffffffffffffffff)*(((((uint128_t)(mycpu->RDI & 0xFFFFFFFFFFFFFFFF)) << 0) | (((uint128_t)(0x0 & 0xFFFFFFFFFFFFFFFF)) << 64))&0xffffffffffffffffffffffffffffffff))&0xffffffffffffffffffffffffffffffff)>>0) & 0xFFFFFFFFFFFFFFFF))&0xFFFFFFFFFFFFFFFF;
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp4eBes3.c:33:269: warning: integer constant is too large for its type
 >RDI & 0xFFFFFFFFFFFFFFFF)) << 0) | (((uint128_t)(0x0 & 0xFFFFFFFFFFFFFFFF)) << 64))&0xffffffffffffffffffffffffffffffff))&0xffffffffffffffffffffffffffffffff)>>0) & 0xFFFFFFFFFFFFFFFF))&0xFFFFFFFFFFFFFFFF;
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp4eBes3.c:33:306: warning: integer constant is too large for its type
 ((uint128_t)(0x0 & 0xFFFFFFFFFFFFFFFF)) << 64))&0xffffffffffffffffffffffffffffffff))&0xffffffffffffffffffffffffffffffff)>>0) & 0xFFFFFFFFFFFFFFFF))&0xFFFFFFFFFFFFFFFF;
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp4eBes3.c:34:126: warning: integer constant is too large for its type
 >RAX & 0xFFFFFFFFFFFFFFFF)) << 0) | (((uint128_t)(0x0 & 0xFFFFFFFFFFFFFFFF)) << 64))&0xffffffffffffffffffffffffffffffff)*(((((uint128_t)(mycpu->RDI & 0xFFFFFFFFFFFFFFFF)) << 0) | (((uint128_t)(0x0 & 0xFFFFFFFFFFFFFFFF)) << 64))&0xffffffffffffffffffffffffffffffff))&0xffffffffffffffffffffffffffffffff)>>64) & 0xFFFFFFFFFFFFFFFF))&0xFFFFFFFFFFFFFFFF;
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp4eBes3.c:34:269: warning: integer constant is too large for its type
 >RDI & 0xFFFFFFFFFFFFFFFF)) << 0) | (((uint128_t)(0x0 & 0xFFFFFFFFFFFFFFFF)) << 64))&0xffffffffffffffffffffffffffffffff))&0xffffffffffffffffffffffffffffffff)>>64) & 0xFFFFFFFFFFFFFFFF))&0xFFFFFFFFFFFFFFFF;
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp4eBes3.c:34:306: warning: integer constant is too large for its type
 ((uint128_t)(0x0 & 0xFFFFFFFFFFFFFFFF)) << 64))&0xffffffffffffffffffffffffffffffff))&0xffffffffffffffffffffffffffffffff)>>64) & 0xFFFFFFFFFFFFFFFF))&0xFFFFFFFFFFFFFFFF;
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "./scripts/miasm.py", line 46, in <module>
    jitter.continue_run(True)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitload.py", line 372, in continue_run
    return self.run_iterator.next()
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitload.py", line 343, in runiter_once
    self.pc = self.runbloc(self.pc)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitload.py", line 300, in runbloc
    return self.jit.runbloc(self.cpu, pc, self.breakpoints_handler.callbacks)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitcore.py", line 180, in runbloc
    self.disbloc(lbl, cpu.vmmngr)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitcore.py", line 164, in disbloc
    self.add_bloc(cur_block)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitcore_gcc.py", line 58, in add_bloc
    check_call(args)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cc', '-O3', '-shared', '-fPIC', '/tmp/tmp4eBes3.c', '-o', '/tmp/tmpvBwUOV.so', '-I/usr/local/lib/python2.7/dist-packages/miasm2/jitter', '-I/usr/include/python2.7', '/usr/local/lib/python2.7/dist-packages/miasm2/jitter/VmMngr.so', '/usr/local/lib/python2.7/dist-packages/miasm2/jitter/arch/JitCore_x86.so']' returned non-zero exit status 1
```

With some older versions there is only warnings and no Error so the emulation continue and there will be no warnings in the next tries. In this case you have to delete */tmp/miasm_cache/* files.

**Comment by commial** [comment]
Hi,

Actually, to perform the multiplication, Miasm does the operation on `size * 2` and then truncate to obtain the high / low part of the result. This way, we can use standard operations / slices, instead of having a specific and complex version on `size` only.

You can give a try to the `llvm` or `python` jitter, which both support arbitrary sized operations.

**Comment by Summus6** [comment]
I tried with python jitter and it wokred (as accepted since it support 128bits).
But I was not expecting to see "128bits errors" on 64bits registers. I understand now ! :)

**Comment by Summus6** [comment]
I close this as it is related to the 128bits issues.
