### ISSUE TITLE
miasm does not build on 32 bits architecture anymore

### ISSUE THREAD

**Issue by guedou** [cea-sec/miasm#762]
`python setup.py build` gives errors related to 128 bits integer on my ARM 32bits laptop:
```
miasm2/jitter/vm_mngr.h:29:19: error: unknown type name '__uint128_t'
 #define uint128_t __uint128_t
```

It used to work fine.

Reverting the following commits, temporarily fixed the issue:
18ac4b21a484265ff50f400ad400a6f028038455
5b209fe29d62f78aefab6f1d8eabb3ed41015439
71bef938419c587e7cc214eb3b8a780de18568bd
23cee4aeb4d667b6ff93b279a8619acf56a70bc3

**Comment by commial** [comment]
This should be fixed with the introduction of big nums. Please re-open if it didn't.

**Comment by guedou** [comment]
Thanks a lot! It compiles fine on my ARMv7, and most of the tests are OK (`Result: 280/283 pass` with `python test_all.py -t llvm,qemu,z3`).

FTR:
```
ERROR x86/unit/access_xmm.py python
Traceback (most recent call last):
  File "x86/unit/access_xmm.py", line 16, in <module>
    assert myjit.cpu.XMM1 == 0x00112233445566778899aabbccddeeffL
AssertionError

ERROR expr_translate.py
Traceback (most recent call last):
  File "expr_translate.py", line 22, in <module>
    for lang in Translator.available_languages()}
  File "expr_translate.py", line 22, in <dictcomp>
    for lang in Translator.available_languages()}
  File "/tmp/miasm/ve_miasm_32/local/lib/python2.7/site-packages/miasm2/ir/translators/translator.py", line 120, in from_expr
    ret = handler(expr)
  File "/tmp/miasm/ve_miasm_32/local/lib/python2.7/site-packages/miasm2/ir/translators/z3_ir.py", line 147, in from_ExprMem
    addr = self.from_expr(expr.arg)
  File "/tmp/miasm/ve_miasm_32/local/lib/python2.7/site-packages/miasm2/ir/translators/translator.py", line 120, in from_expr
    ret = handler(expr)
  File "/tmp/miasm/ve_miasm_32/local/lib/python2.7/site-packages/miasm2/ir/translators/z3_ir.py", line 158, in from_ExprCompose
    e = z3.Extract(arg.size-1, 0, self.from_expr(arg))
AttributeError: 'module' object has no attribute 'Extract'

ERROR run_with_linuxenv.py -v -p /(.*lib.*\.so(\.\d+)?)|(/etc/ld.so.*)|(.*magic.*)|(/bin/ls) --jitter gcc /usr/bin/file /bin/ls
WARNING: address 0x5D is not mapped in virtual memory:
WARNING: address 0x5D is not mapped in virtual memory:
Traceback (most recent call last):
  File "run_with_linuxenv.py", line 85, in <module>
    jitter.continue_run()
  File "/tmp/miasm/ve_miasm_32/local/lib/python2.7/site-packages/miasm2/jitter/jitload.py", line 387, in continue_run
    return self.run_iterator.next()
  File "/tmp/miasm/ve_miasm_32/local/lib/python2.7/site-packages/miasm2/jitter/jitload.py", line 355, in runiter_once
    assert(self.get_exception() == 0)
AssertionError
```
