### ISSUE TITLE
STT_GNU_IFUNC not defined in some ELF binaries

### ISSUE THREAD

**Issue by icecr4ck** [cea-sec/miasm#824]
Hello,

There is an issue regarding the declaration of the STT_GNU_IFUNC symbol in ELF binaries. 

More specifically, when the symbol is not defined in the binary, opening it with the `Container.from_stream` function produces the following error.

```
Traceback (most recent call last):
  File "miasm/example/disasm/file.py", line 12, in <module>
    cont = Container.from_stream(open(sys.argv[1]))
  File "/usr/local/lib/python2.7/site-packages/miasm2/analysis/binary.py", line 74, in from_stream
    return Container.from_string(stream.read(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/miasm2/analysis/binary.py", line 46, in from_string
    return container_type(data, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/miasm2/analysis/binary.py", line 95, in __init__
    self.parse(data, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/miasm2/analysis/binary.py", line 210, in parse
    fill_loc_db_with_symbols(self._executable, self.loc_db, addr)
  File "/usr/local/lib/python2.7/site-packages/miasm2/jitter/loader/elf.py", line 92, in fill_loc_db_with_symbols
    elf_csts.STT_GNU_IFUNC,
AttributeError: 'module' object has no attribute 'STT_GNU_IFUNC'
```

**Comment by commial** [comment]
Hi,

You probably want to update your elfesteem installation, the constant has been introduced here: https://github.com/serpilliere/elfesteem/commit/cd247fb6e902f3451349d2c4188513c697d506f1

**Comment by icecr4ck** [comment]
Thanks, it seems to resolve this issue. However, I could not update elfesteem using `pip install --upgrade`, maybe it is related to this issue: serpilliere/elfesteem#13

**Comment by commial** [comment]
Indeed. The preferred way to install elfesteem, at least for now, is by using the clone / "setup.py install" method.
