### ISSUE TITLE
Jitter: Python: TypeError: arg must be str

### ISSUE THREAD

**Issue by 0vercl0k** [cea-sec/miasm#841]
I've hit this exception while playing with miasm (commit @1e994249defba6024c48796443a66889466b5326). A repro is attached to this issue (
[8840f219d6e86c9ce30c3478a787a51a-python.zip](https://github.com/cea-sec/miasm/files/2344993/8840f219d6e86c9ce30c3478a787a51a-python.zip)):

```

[8840f219d6e86c9ce30c3478a787a51a-python.zip](https://github.com/cea-sec/miasm/files/2344941/8840f219d6e86c9ce30c3478a787a51a-python.zip)
RAX DEADBEEFBAADC0DE RBX 0000003BC15FDB60 RCX 0000020FE9626000 RDX 0000003BC15FDB60 RSI 0000020FE9CDB098 RDI 0000003BC15FDCF0 RSP 0000003BC15FD778 RBP 0000020FE9626000 RIP 00007FF6FFB81FBA
R8  0000003BC15FDCF0 R9  0000020FE9CDB098 R10 0000020FE9D4C948 R11 0000000000000013 R12 0000020FE9626068 R13 00007FF7010724D8 R14 DEADBEEFBAADC0DE R15 0000020FE9626000 zf 0 nf 0 of 0 cf 0
7ff6ffb81fba MOV        BYTE PTR [0xEF05EDE900698B], AL
WARNING: address 0xEF05EDE900698B is not mapped in virtual memory:
Traceback (most recent call last):
  File "8840f219d6e86c9ce30c3478a787a51a-python.py", line 84, in <module>
    jitter.continue_run()
  File "c:\work\codes\miasm\build\lib.win-amd64-2.7\miasm2\jitter\jitload.py", line 387, in continue_run
    return self.run_iterator.next()
  File "c:\work\codes\miasm\build\lib.win-amd64-2.7\miasm2\jitter\jitload.py", line 358, in runiter_once
    self.pc = self.run_at(self.pc)
  File "c:\work\codes\miasm\build\lib.win-amd64-2.7\miasm2\jitter\jitload.py", line 315, in run_at
    set(self.breakpoints_handler.callbacks.keys())
  File "c:\work\codes\miasm\build\lib.win-amd64-2.7\miasm2\jitter\jitcore.py", line 200, in run_at
    self.options["max_exec_per_call"])
  File "c:\work\codes\miasm\build\lib.win-amd64-2.7\miasm2\jitter\jitcore_python.py", line 146, in exec_wrapper
    return fc_ptr(cpu)
  File "c:\work\codes\miasm\build\lib.win-amd64-2.7\miasm2\jitter\jitcore_python.py", line 106, in myfunc
    exec_engine.eval_updt_assignblk(assignblk)
  File "c:\work\codes\miasm\build\lib.win-amd64-2.7\miasm2\ir\symbexec.py", line 1031, in eval_updt_assignblk
    self.apply_change(dst, src)
  File "c:\work\codes\miasm\build\lib.win-amd64-2.7\miasm2\ir\symbexec.py", line 1019, in apply_change
    self.mem_write(dst, src)
  File "c:\work\codes\miasm\build\lib.win-amd64-2.7\miasm2\ir\symbexec.py", line 1177, in mem_write
    self.func_write(self, dst, src)
  File "c:\work\codes\miasm\build\lib.win-amd64-2.7\miasm2\jitter\emulatedsymbexec.py", line 80, in _func_write
    self.cpu.set_mem(addr, content)
TypeError: arg must be str
```

Cheers

**Comment by serpilliere** [comment]
Hi!
Ok. Here is the explanation:
You execute an instruction which does a memory deref on an non existing page.
The trick is that in *python* jitter, it seems not to raise the error on the CPU, so it messes the jitter.
The code does its job with the llvm/gcc jitter.

I will analyse this.
