### ISSUE TITLE
Jitter: Python: AssertionError in simp_cst_propagation

### ISSUE THREAD

**Issue by 0vercl0k** [cea-sec/miasm#842]
I've hit this exception while playing with miasm (commit @1e994249defba6024c48796443a66889466b5326). A repro is attached to this issue ([c11e3b1ad4810e7c2e7294f198ebe4b8-python.zip](https://github.com/cea-sec/miasm/files/2345005/c11e3b1ad4810e7c2e7294f198ebe4b8-python.zip)) (you can grab the `js.dmp` file attached in #841):

```
>python c11e3b1ad4810e7c2e7294f198ebe4b8-python.py

RAX DEADBEEFBAADC0DE RBX 0000003BC15FDB60 RCX 0000020FE9626000 RDX 0000003BC15FDB60 RSI 0000020FE9CDB098 RDI 0000003BC15FDCF0 RSP 0000003BC15FD778 RBP 0000020FE9626000 RIP 00007FF6FFB816D9
R8  0000003BC15FDCF0 R9  0000020FE9CDB098 R10 0000020FE9D4C948 R11 0000000000000013 R12 0000020FE9626068 R13 00007FF7010724D8 R14 DEADBEEFBAADC0DE R15 0000020FE9626000 zf 0 nf 0 of 0 cf 0
7ff6ffb816d9 AAM        0x0
Traceback (most recent call last):
  File "c11e3b1ad4810e7c2e7294f198ebe4b8-python.py", line 104, in <module>
    jitter.continue_run()
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\jitload.py", line 387, in continue_run
    return self.run_iterator.next()
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\jitload.py", line 358, in runiter_once
    self.pc = self.run_at(self.pc)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\jitload.py", line 315, in run_at
    set(self.breakpoints_handler.callbacks.keys())
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\jitcore.py", line 200, in run_at
    self.options["max_exec_per_call"])
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\jitcore_python.py", line 146, in exec_wrapper
    return fc_ptr(cpu)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\jitcore_python.py", line 106, in myfunc
    exec_engine.eval_updt_assignblk(assignblk)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 1029, in eval_updt_assignblk
    dst_src = self.eval_assignblk(assignblk)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 999, in eval_assignblk
    src = self.eval_expr(src, eval_cache)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 953, in eval_expr
    ret = self.eval_expr_visitor(expr, cache=eval_cache)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 878, in eval_expr_visitor
    ret = func(new_expr, cache=cache)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 916, in eval_exprcond
    cond = self.eval_expr_visitor(expr.cond, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 878, in eval_expr_visitor
    ret = func(new_expr, cache=cache)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 941, in eval_exprcompose
    args.append(self.eval_expr_visitor(arg, **kwargs))
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 879, in eval_expr_visitor
    ret = self.expr_simp(ret)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\expression\simplifications.py", line 166, in __call__
    return self.expr_simp_wrapper(expression, callback)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\expression\simplifications.py", line 162, in expr_simp_wrapper
    return expression.visit(callback, lambda e: e not in self.simplified_exprs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\expression\expression.py", line 101, in wrapped
    expr_new2 = callback(expr_new)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\expression\simplifications.py", line 138, in expr_simp
    e_new = self.apply_simp(expression.canonize())
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\expression\simplifications.py", line 115, in apply_simp
    expression = simp_func(self, expression)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\expression\simplifications_common.py", line 87, in simp_cst_propagation
    assert int2.arg.arg
AssertionError
```

Cheers

**Comment by serpilliere** [comment]
Hi!
It seems that the code tries to do a division by 0, so the symbolic engine stops on the assert...
The two values in the symbolic emulation are *concrete* here, and it does a 0/0, which is simplified, and raises the assertion.
I admit the code is not clear here, and I will add a comment.
But the question is open here:
what can we do in such a case?
