### ISSUE TITLE
Jitter: Python: RuntimeError: cannot find address in _func_read

### ISSUE THREAD

**Issue by 0vercl0k** [cea-sec/miasm#843]
I've hit this exception while playing with miasm (commit @1e994249defba6024c48796443a66889466b5326). A repro is attached to this issue (
[da0a767522e2090a1b012066d07b3df7-python.zip](https://github.com/cea-sec/miasm/files/2345040/da0a767522e2090a1b012066d07b3df7-python.zip)
) (you can grab the js.dmp file attached in #841):

```
>python da0a767522e2090a1b012066d07b3df7-python.py

RAX DEADBEEFBAADC0DE RBX 0000003BC15FDB60 RCX 0000020FE9626000 RDX 0000003BC15FDB60 RSI 0000020FE9CDB098 RDI 0000003BC15FDCF0 RSP 0000003BC15FD778 RBP 0000020FE9626000 RIP 00007FF6FFB81FFA
R8  0000003BC15FDCF0 R9  0000020FE9CDB098 R10 0000020FE9D4C948 R11 0000000000000013 R12 0000020FE9626068 R13 00007FF7010724D8 R14 DEADBEEFBAADC0DE R15 0000020FE9626000 zf 0 nf 0 of 0 cf 0
7ff6ffb81ffa JMP        loc_key_1
RAX DEADBEEFBAADC0DE RBX 0000003BC15FDB60 RCX 0000020FE9626000 RDX 0000003BC15FDB60 RSI 0000020FE9CDB098 RDI 0000003BC15FDCF0 RSP 0000003BC15FD778 RBP 0000020FE9626000 RIP 00007FF7000F0B20
R8  0000003BC15FDCF0 R9  0000020FE9CDB098 R10 0000020FE9D4C948 R11 0000000000000013 R12 0000020FE9626068 R13 00007FF7010724D8 R14 DEADBEEFBAADC0DE R15 0000020FE9626000 zf 0 nf 0 of 0 cf 0
7ff7000f0b20 PUSH       RBX
RAX DEADBEEFBAADC0DE RBX 0000003BC15FDB60 RCX 0000020FE9626000 RDX 0000003BC15FDB60 RSI 0000020FE9CDB098 RDI 0000003BC15FDCF0 RSP 0000003BC15FD770 RBP 0000020FE9626000 RIP 00007FF7000F0B20
R8  0000003BC15FDCF0 R9  0000020FE9CDB098 R10 0000020FE9D4C948 R11 0000000000000013 R12 0000020FE9626068 R13 00007FF7010724D8 R14 DEADBEEFBAADC0DE R15 0000020FE9626000 zf 0 nf 0 of 0 cf 0
7ff7000f0b22 SUB        RSP, 0x30
RAX DEADBEEFBAADC0DE RBX 0000003BC15FDB60 RCX 0000020FE9626000 RDX 0000003BC15FDB60 RSI 0000020FE9CDB098 RDI 0000003BC15FDCF0 RSP 0000003BC15FD740 RBP 0000020FE9626000 RIP 00007FF7000F0B22
R8  0000003BC15FDCF0 R9  0000020FE9CDB098 R10 0000020FE9D4C948 R11 0000000000000013 R12 0000020FE9626068 R13 00007FF7010724D8 R14 DEADBEEFBAADC0DE R15 0000020FE9626000 zf 0 nf 0 of 0 cf 0
7ff7000f0b26 MOV        RBX, RCX
RAX DEADBEEFBAADC0DE RBX 0000020FE9626000 RCX 0000020FE9626000 RDX 0000003BC15FDB60 RSI 0000020FE9CDB098 RDI 0000003BC15FDCF0 RSP 0000003BC15FD740 RBP 0000020FE9626000 RIP 00007FF7000F0B26
R8  0000003BC15FDCF0 R9  0000020FE9CDB098 R10 0000020FE9D4C948 R11 0000000000000013 R12 0000020FE9626068 R13 00007FF7010724D8 R14 DEADBEEFBAADC0DE R15 0000020FE9626000 zf 0 nf 0 of 0 cf 0
7ff7000f0b29 ADD        RCX, 0x150
RAX DEADBEEFBAADC0DE RBX 0000020FE9626000 RCX 0000020FE9626150 RDX 0000003BC15FDB60 RSI 0000020FE9CDB098 RDI 0000003BC15FDCF0 RSP 0000003BC15FD740 RBP 0000020FE9626000 RIP 00007FF7000F0B29
R8  0000003BC15FDCF0 R9  0000020FE9CDB098 R10 0000020FE9D4C948 R11 0000000000000013 R12 0000020FE9626068 R13 00007FF7010724D8 R14 DEADBEEFBAADC0DE R15 0000020FE9626000 zf 0 nf 0 of 0 cf 0
7ff7000f0b30 MOV        RDX, QWORD PTR [RCX]
RAX DEADBEEFBAADC0DE RBX 0000020FE9626000 RCX 0000020FE9626150 RDX 0000000000001AA8 RSI 0000020FE9CDB098 RDI 0000003BC15FDCF0 RSP 0000003BC15FD740 RBP 0000020FE9626000 RIP 00007FF7000F0B30
R8  0000003BC15FDCF0 R9  0000020FE9CDB098 R10 0000020FE9D4C948 R11 0000000000000013 R12 0000020FE9626068 R13 00007FF7010724D8 R14 DEADBEEFBAADC0DE R15 0000020FE9626000 zf 0 nf 0 of 0 cf 0
7ff7000f0b33 CMP        QWORD PTR [RDX], RCX
WARNING: address 0x1AA8 is not mapped in virtual memory:
Traceback (most recent call last):
  File "da0a767522e2090a1b012066d07b3df7-python.py", line 98, in <module>
    jitter.continue_run()
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\jitload.py", line 387, in continue_run
    return self.run_iterator.next()
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\jitload.py", line 358, in runiter_once
    self.pc = self.run_at(self.pc)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\jitload.py", line 315, in run_at
    set(self.breakpoints_handler.callbacks.keys())
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\jitcore.py", line 200, in run_at
    self.options["max_exec_per_call"])
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\jitcore_python.py", line 146, in exec_wrapper
    return fc_ptr(cpu)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\jitcore_python.py", line 106, in myfunc
    exec_engine.eval_updt_assignblk(assignblk)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 1029, in eval_updt_assignblk
    dst_src = self.eval_assignblk(assignblk)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 999, in eval_assignblk
    src = self.eval_expr(src, eval_cache)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 953, in eval_expr
    ret = self.eval_expr_visitor(expr, cache=eval_cache)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 878, in eval_expr_visitor
    ret = func(new_expr, cache=cache)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 924, in eval_exprslice
    arg = self.eval_expr_visitor(expr.arg, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 878, in eval_expr_visitor
    ret = func(new_expr, cache=cache)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 932, in eval_exprop
    arg = self.eval_expr_visitor(oarg, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 878, in eval_expr_visitor
    ret = func(new_expr, cache=cache)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 911, in eval_exprmem
    ret = self.mem_read(mem)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 1158, in mem_read
    ret = self.func_read(part)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\emulatedsymbexec.py", line 49, in _func_read
    value = self.cpu.get_mem(addr, size)
RuntimeError: cannot find address
```

Cheers

**Comment by serpilliere** [comment]
It's the same bug as in the #841
On llvm/gcc, it's ok, not on python.
I definitively  need to check what's the heck in the python jitter

**Comment by 0vercl0k** [comment]
Hehe, do you want me to close this issue if it's a duplicate?

Cheers

Le sam. 8 sept. 2018 à 08:27, serpilliere <notifications@github.com> a
écrit :

**Comment by serpilliere** [comment]
nop, don't bother: It will be there to remain me every use case to fix :smiley:
