### ISSUE TITLE
Jitter: Python: AttributeError: 'ExprOp' object has no attribute 'arg' in _func_write

### ISSUE THREAD

**Issue by 0vercl0k** [cea-sec/miasm#844]
I've hit this exception while playing with miasm (commit @1e994249defba6024c48796443a66889466b5326). A repro is attached to this issue (
[3932a91d51da9de140f7a4a27d40afa1-python.zip](https://github.com/cea-sec/miasm/files/2345048/3932a91d51da9de140f7a4a27d40afa1-python.zip)
) (you can grab the js.dmp file attached in #841):

```
>python 3932a91d51da9de140f7a4a27d40afa1-python.py

RAX DEADBEEFBAADC0DE RBX 0000003BC15FDB60 RCX 0000020FE9626000 RDX 0000003BC15FDB60 RSI 0000020FE9CDB098 RDI 0000003BC15FDCF0 RSP 0000003BC15FD778 RBP 0000020FE9626000 RIP 00007FF6FFB81D9A
R8  0000003BC15FDCF0 R9  0000020FE9CDB098 R10 0000020FE9D4C948 R11 0000000000000013 R12 0000020FE9626068 R13 00007FF7010724D8 R14 DEADBEEFBAADC0DE R15 0000020FE9626000 zf 0 nf 0 of 0 cf 0
7ff6ffb81d9a WRMSR
Traceback (most recent call last):
  File "3932a91d51da9de140f7a4a27d40afa1-python.py", line 84, in <module>
    jitter.continue_run()
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\jitload.py", line 387, in continue_run
    return self.run_iterator.next()
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\jitload.py", line 358, in runiter_once
    self.pc = self.run_at(self.pc)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\jitload.py", line 315, in run_at
    set(self.breakpoints_handler.callbacks.keys())
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\jitcore.py", line 200, in run_at
    self.options["max_exec_per_call"])
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\jitcore_python.py", line 146, in exec_wrapper
    return fc_ptr(cpu)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\jitcore_python.py", line 106, in myfunc
    exec_engine.eval_updt_assignblk(assignblk)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 1031, in eval_updt_assignblk
    self.apply_change(dst, src)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 1019, in apply_change
    self.mem_write(dst, src)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\ir\symbexec.py", line 1177, in mem_write
    self.func_write(self, dst, src)
  File "C:\ProgramData\Anaconda2\lib\site-packages\miasm-2.0-py2.7-win-amd64.egg\miasm2\jitter\emulatedsymbexec.py", line 70, in _func_write
    addr = dest.arg.arg.arg
AttributeError: 'ExprOp' object has no attribute 'arg'
```

Cheers

**Comment by serpilliere** [comment]
There is a bug in the semantic of msr.
Actually, it's implemented as a read on a 'special' symbolic array based on the base address "msr".
I will change this to simply set it as a privilegied instruction, as sti for example.
It should raise a cpu exception.
