### ISSUE TITLE
arm:- Unknown mnemo LDRSBNE

### ISSUE THREAD

**Issue by hax0kartik** [cea-sec/miasm#978]
Traceback (most recent call last):
  File "test.py", line 40, in <module>
    sb.call(GetLastError, JpegStruct_S)
  File "/usr/lib/python2.7/site-packages/miasm2/analysis/sandbox.py", line 705, in call
    super(self.__class__, self).call(prepare_cb, addr, *args)
  File "/usr/lib/python2.7/site-packages/miasm2/analysis/sandbox.py", line 139, in call
    self.jitter.continue_run()
  File "/usr/lib/python2.7/site-packages/miasm2/jitter/jitload.py", line 387, in continue_run
    return self.run_iterator.next()
  File "/usr/lib/python2.7/site-packages/miasm2/jitter/jitload.py", line 358, in runiter_once
    self.pc = self.run_at(self.pc)
  File "/usr/lib/python2.7/site-packages/miasm2/jitter/jitload.py", line 315, in run_at
    set(self.breakpoints_handler.callbacks.keys())
  File "/usr/lib/python2.7/site-packages/miasm2/jitter/jitcore.py", line 176, in run_at
    cur_block = self.disasm_and_jit_block(offset, cpu.vmmngr)
  File "/usr/lib/python2.7/site-packages/miasm2/jitter/jitcore.py", line 153, in disasm_and_jit_block
    self.add_block(cur_block)
  File "/usr/lib/python2.7/site-packages/miasm2/jitter/jitcore_gcc.py", line 52, in add_block
    func_code = self.gen_c_code(block)
  File "/usr/lib/python2.7/site-packages/miasm2/jitter/jitcore_cc_base.py", line 97, in gen_c_code
    out = self.codegen.gen_c(block, log_mn=self.log_mn, log_regs=self.log_regs)
  File "/usr/lib/python2.7/site-packages/miasm2/jitter/codegen.py", line 631, in gen_c
    irblocks_list = self.block2assignblks(block)
  File "/usr/lib/python2.7/site-packages/miasm2/arch/arm/jit.py", line 43, in block2assignblks
    assignblk_head, assignblks_extra = self.ir_arch.instr2ir(instr)
  File "/usr/lib/python2.7/site-packages/miasm2/ir/ir.py", line 741, in instr2ir
    ir_bloc_cur, extra_irblocks = self.get_ir(instr)
  File "/usr/lib/python2.7/site-packages/miasm2/arch/arm/sem.py", line 1697, in get_ir
    instr_ir, extra_ir = get_mnemo_expr(self, instr, *args)
  File "/usr/lib/python2.7/site-packages/miasm2/arch/arm/sem.py", line 1646, in get_mnemo_expr
    raise ValueError('unknown mnemo %s' % instr)
ValueError: unknown mnemo LDRSBNE    R0, [R0, 0x44]
I'm not sure what's wrong, ldrsb seems to be already implemented in arm/sem.py

**Comment by serpilliere** [comment]
erf, I see the problem: the instruction has been described in the "cond_m1" which means:
the mnemonic can accept conditional code, but add it a letter before the end of the mnemoic...
Example:`ldrsb XXXXXX` with conditional code is traducted by: `ldrsneb` not by: `ldrnbne`
Maybe it must be moved in `cond_m0` array.

I didn't check what the documentation says about this

**Comment by hax0kartik** [comment]
I tried what you said and that fixes this issue

**Comment by serpilliere** [comment]
Ho great!
Do you want to to a PR?
Or maybe I will have a look at the documentation.
I don't known which one is right between the name from the disassembler or from the ir
(ie `ldrsbne` or `ldrsneb`)

**Comment by hax0kartik** [comment]
`LDRNESB` according to IDA

**Comment by serpilliere** [comment]
Thank you @hax0kartik 
by the way, I didn't find the nop in the my documentation (arm architecture reference manual)
Have you got a reference or something?

**Comment by hax0kartik** [comment]
A completely unrelated question, do we have an IRC server or something like that for discussion?
