### ISSUE TITLE
Test Errors Encountered. Help Appreciated.

### ISSUE THREAD

**Issue by davidleejy** [cea-sec/miasm#994]
Hello, while running `python test/test_all.py`, some errors were encountered. Might anyone here have ideas as to what I might have done wrong? (i have done pip install z3-solver, llvmlite, and other packages)

The following are excerpts showing errors from stdout when `test_all.py` was ran:

**Error 1**
```
TEST/ARCH arm/arch.py gcc 
ERROR x86/unit/mn_div.py llvm
```

**Error 2**
```
ERROR testqemu64.py test-x86_64 test_mul expected_x86_64/test_mul.exp --jitter llvm
[WARNING]: Create dummy entry for 'xxx.dll'
```

**Error 3**
```
ERROR run_with_linuxenv.py -v -p /(.*lib.*\.so(\.\d+)?)|(/etc/ld.so.*)|(.*magic.*)|(/bin/ls) --jitter llvm /usr/bin/file /bin/ls
[DEBUG]: sys_brk(0)
[DEBUG]: -> 74000000
[DEBUG]: sys_newuname(123faf4)
[DEBUG]: -> 0
[DEBUG]: sys_access(/etc/ld.so.nohwcap, 0)
[DEBUG]: -> ffffffffffffffff
[DEBUG]: sys_access(/etc/ld.so.preload, 4)
[DEBUG]: -> ffffffffffffffff
[DEBUG]: sys_open('/etc/ld.so.cache', 80000, 1)
[DEBUG]: -> 3
[DEBUG]: sys_fstat(3, 123f4c4)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(0, 24796, 1, 2, 3, 0)
[DEBUG]: -> 80027000
[DEBUG]: sys_close(3)
[DEBUG]: -> 0
[DEBUG]: sys_access(/etc/ld.so.nohwcap, 0)
[DEBUG]: -> ffffffffffffffff
[DEBUG]: sys_open('/usr/lib/x86_64-linux-gnu/libmagic.so.1', 80000, 80227168)
[DEBUG]: -> 4
[DEBUG]: sys_read(4, 123f67c, 340)
[DEBUG]: -> 340
[DEBUG]: sys_fstat(4, 123f514)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(0, 21f5a0, 5, 802, 4, 0)
[DEBUG]: -> 80229000
[DEBUG]: sys_mprotect(80247000, 200000, 0)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(80447000, 2000, 3, 812, 4, 1e000)
[DEBUG]: -> 80447000
[DEBUG]: sys_close(4)
[DEBUG]: -> 0
[DEBUG]: sys_access(/etc/ld.so.nohwcap, 0)
[DEBUG]: -> ffffffffffffffff
[DEBUG]: sys_open('/lib/x86_64-linux-gnu/libc.so.6', 80000, 80227168)
[DEBUG]: -> 5
[DEBUG]: sys_read(5, 123f64c, 340)
[DEBUG]: -> 340
[DEBUG]: sys_fstat(5, 123f4e4)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(0, 1000, 3, 22, ffffffffffffffff, 0)
[DEBUG]: -> 8004c000
[DEBUG]: sys_mmap(0, 3c99a0, 5, 802, 5, 0)
[DEBUG]: -> 8044a000
[DEBUG]: sys_mprotect(8060a000, 200000, 0)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(8080a000, 6000, 3, 812, 5, 1c0000)
[DEBUG]: -> 8080a000
[DEBUG]: sys_mmap(80810000, 39a0, 3, 32, ffffffffffffffff, 0)
[DEBUG]: -> 80810000
[DEBUG]: sys_close(5)
[DEBUG]: -> 0
[DEBUG]: sys_access(/etc/ld.so.nohwcap, 0)
[DEBUG]: -> ffffffffffffffff
[DEBUG]: sys_open('/lib/x86_64-linux-gnu/libz.so.1', 80000, 802278e0)
[DEBUG]: -> 6
[DEBUG]: sys_read(6, 123f51c, 340)
[DEBUG]: -> 340
[DEBUG]: sys_fstat(6, 123f3b4)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(0, 219128, 5, 802, 6, 0)
[DEBUG]: -> 80814000
[DEBUG]: sys_mprotect(8082d000, 1ff000, 0)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(80a2c000, 2000, 3, 812, 6, 18000)
[DEBUG]: -> 80a2c000
[DEBUG]: sys_close(6)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(0, 1000, 3, 22, ffffffffffffffff, 0)
[DEBUG]: -> 8004e000
```

**Many errors here:**
```
ERROR smt2.py
Traceback (most recent call last):
  File "smt2.py", line 39, in <module>
    s.add(e_z3 != smt2_z3)
  File "/home/dl/anaconda3/envs/sybil/lib/python2.7/site-packages/z3/z3.py", line 882, in __ne__
    a, b = _coerce_exprs(self, other)
  File "/home/dl/anaconda3/envs/sybil/lib/python2.7/site-packages/z3/z3.py", line 1029, in _coerce_exprs
    b = s.cast(b)
  File "/home/dl/anaconda3/envs/sybil/lib/python2.7/site-packages/z3/z3.py", line 1319, in cast
    _z3_assert(is_expr(val), "True, False or Z3 Boolean expression expected. Received %s" % val)
  File "/home/dl/anaconda3/envs/sybil/lib/python2.7/site-packages/z3/z3.py", line 91, in _z3_assert
    raise Z3Exception(msg)
z3.z3types.Z3Exception: True, False or Z3 Boolean expression expected. Received [If(And(Extract(7,
                0,
                Extract(15, 0, Extract(31, 0, a) + b)*c) <<
        (LShR(d, 5 & 8 - 1) | d << 8 - (5 & 8 - 1)) !=
        0,
        True),
    a + 100,
    22) ==
 If(And(e +
        (1 ^
         Extract(0, 0, Extract(7, 0, a)) ^
         Extract(1, 1, Extract(7, 0, a)) ^
         Extract(2, 2, Extract(7, 0, a)) ^
         Extract(3, 3, Extract(7, 0, a)) ^
         Extract(4, 4, Extract(7, 0, a)) ^
         Extract(5, 5, Extract(7, 0, a)) ^
         Extract(6, 6, Extract(7, 0, a)) ^
         Extract(7, 7, Extract(7, 0, a))) !=
        0,
        True),
    Concat(mem64[a*a + 7],
           Concat(mem64[a*a + 6],
                  Concat(mem64[a*a + 5],
                         Concat(mem64[a*a + 4],
                                Concat(mem64[a*a + 3],
                                       Concat(mem64[a*a + 2],
                                        Concat(mem64[a*a + 1],
                                        mem64[a*a]))))))),
    Concat(mem64[a + 7],
           Concat(mem64[a + 6],
                  Concat(mem64[a + 5],
                         Concat(mem64[a + 4],
                                Concat(mem64[a + 3],
                                       Concat(mem64[a + 2],
                                        Concat(mem64[a + 1],
                                        mem64[a]))))))))]

ERROR run_with_linuxenv.py -v -p /(.*lib.*\.so(\.\d+)?)|(/etc/ld.so.*)|(.*magic.*)|(/bin/ls) --jitter gcc /usr/bin/file /bin/ls
[DEBUG]: sys_brk(0)
[DEBUG]: -> 74000000
[DEBUG]: sys_newuname(123faf4)
[DEBUG]: -> 0
[DEBUG]: sys_access(/etc/ld.so.nohwcap, 0)
[DEBUG]: -> ffffffffffffffff
[DEBUG]: sys_access(/etc/ld.so.preload, 4)
[DEBUG]: -> ffffffffffffffff
[DEBUG]: sys_open('/etc/ld.so.cache', 80000, 1)
[DEBUG]: -> 3
[DEBUG]: sys_fstat(3, 123f4c4)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(0, 24796, 1, 2, 3, 0)
[DEBUG]: -> 80027000
[DEBUG]: sys_close(3)
[DEBUG]: -> 0
[DEBUG]: sys_access(/etc/ld.so.nohwcap, 0)
[DEBUG]: -> ffffffffffffffff
[DEBUG]: sys_open('/usr/lib/x86_64-linux-gnu/libmagic.so.1', 80000, 80227168)
[DEBUG]: -> 4
[DEBUG]: sys_read(4, 123f67c, 340)
[DEBUG]: -> 340
[DEBUG]: sys_fstat(4, 123f514)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(0, 21f5a0, 5, 802, 4, 0)
[DEBUG]: -> 80229000
[DEBUG]: sys_mprotect(80247000, 200000, 0)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(80447000, 2000, 3, 812, 4, 1e000)
[DEBUG]: -> 80447000
[DEBUG]: sys_close(4)
[DEBUG]: -> 0
[DEBUG]: sys_access(/etc/ld.so.nohwcap, 0)
[DEBUG]: -> ffffffffffffffff
[DEBUG]: sys_open('/lib/x86_64-linux-gnu/libc.so.6', 80000, 80227168)
[DEBUG]: -> 5
[DEBUG]: sys_read(5, 123f64c, 340)
[DEBUG]: -> 340
[DEBUG]: sys_fstat(5, 123f4e4)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(0, 1000, 3, 22, ffffffffffffffff, 0)
[DEBUG]: -> 8004c000
[DEBUG]: sys_mmap(0, 3c99a0, 5, 802, 5, 0)
[DEBUG]: -> 8044a000
[DEBUG]: sys_mprotect(8060a000, 200000, 0)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(8080a000, 6000, 3, 812, 5, 1c0000)
[DEBUG]: -> 8080a000
[DEBUG]: sys_mmap(80810000, 39a0, 3, 32, ffffffffffffffff, 0)
[DEBUG]: -> 80810000
[DEBUG]: sys_close(5)
[DEBUG]: -> 0
[DEBUG]: sys_access(/etc/ld.so.nohwcap, 0)
[DEBUG]: -> ffffffffffffffff
[DEBUG]: sys_open('/lib/x86_64-linux-gnu/libz.so.1', 80000, 802278e0)
[DEBUG]: -> 6
[DEBUG]: sys_read(6, 123f51c, 340)
[DEBUG]: -> 340
[DEBUG]: sys_fstat(6, 123f3b4)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(0, 219128, 5, 802, 6, 0)
[DEBUG]: -> 80814000
[DEBUG]: sys_mprotect(8082d000, 1ff000, 0)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(80a2c000, 2000, 3, 812, 6, 18000)
[DEBUG]: -> 80a2c000
[DEBUG]: sys_close(6)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(0, 1000, 3, 22, ffffffffffffffff, 0)
[DEBUG]: -> 8004e000
[DEBUG]: sys_mmap(0, 1000, 3, 22, ffffffffffffffff, 0)
[DEBUG]: -> 80050000
[DEBUG]: sys_mmap(0, 1000, 3, 22, ffffffffffffffff, 0)
[DEBUG]: -> 80052000
[DEBUG]: sys_arch_prctl(ARCH_SET_FS, 80050700)
[DEBUG]: -> 0
[DEBUG]: sys_mprotect(8080a000, 4000, 1)
[DEBUG]: -> 0
[DEBUG]: sys_mprotect(80a2c000, 1000, 1)
[DEBUG]: -> 0
[DEBUG]: sys_mprotect(80447000, 1000, 1)
[DEBUG]: -> 0
[DEBUG]: sys_mprotect(603000, 1000, 1)
[DEBUG]: -> 0
[DEBUG]: sys_mprotect(80225000, 1000, 1)
[DEBUG]: -> 0
[DEBUG]: sys_munmap(80027000, 24796)
[DEBUG]: -> 0
Traceback (most recent call last):
  File "run_with_linuxenv.py", line 84, in <module>
    jitter.continue_run()
  File "/home/dl/anaconda3/envs/sybil/lib/python2.7/site-packages/miasm2/jitter/jitload.py", line 401, in continue_run
    return self.run_iterator.next()
  File "/home/dl/anaconda3/envs/sybil/lib/python2.7/site-packages/miasm2/jitter/jitload.py", line 372, in runiter_once
    self.pc = self.run_at(self.pc)
  File "/home/dl/anaconda3/envs/sybil/lib/python2.7/site-packages/miasm2/jitter/jitload.py", line 329, in run_at
    set(self.breakpoints_handler.callbacks.keys())
  File "/home/dl/anaconda3/envs/sybil/lib/python2.7/site-packages/miasm2/jitter/jitcore.py", line 176, in run_at
    cur_block = self.disasm_and_jit_block(offset, cpu.vmmngr)
  File "/home/dl/anaconda3/envs/sybil/lib/python2.7/site-packages/miasm2/jitter/jitcore.py", line 153, in disasm_and_jit_block
    self.add_block(cur_block)
  File "/home/dl/anaconda3/envs/sybil/lib/python2.7/site-packages/miasm2/jitter/jitcore_gcc.py", line 52, in add_block
    func_code = self.gen_c_code(block)
  File "/home/dl/anaconda3/envs/sybil/lib/python2.7/site-packages/miasm2/jitter/jitcore_cc_base.py", line 97, in gen_c_code
    out = self.codegen.gen_c(block, log_mn=self.log_mn, log_regs=self.log_regs)
  File "/home/dl/anaconda3/envs/sybil/lib/python2.7/site-packages/miasm2/jitter/codegen.py", line 631, in gen_c
    irblocks_list = self.block2assignblks(block)
  File "/home/dl/anaconda3/envs/sybil/lib/python2.7/site-packages/miasm2/jitter/codegen.py", line 164, in block2assignblks
    assignblk_head, assignblks_extra = self.ir_arch.instr2ir(instr)
  File "/home/dl/anaconda3/envs/sybil/lib/python2.7/site-packages/miasm2/ir/ir.py", line 741, in instr2ir
    ir_bloc_cur, extra_irblocks = self.get_ir(instr)
  File "/home/dl/anaconda3/envs/sybil/lib/python2.7/site-packages/miasm2/arch/x86/sem.py", line 5652, in get_ir
    "Mnemonic %s not implemented" % instr.name)
NotImplementedError: Mnemonic FXSAVE not implemented

ERROR z3_ir.py
Traceback (most recent call last):
  File "z3_ir.py", line 102, in <module>
    [(0xdeadbeef, 2), (0xdeadbeef + 3, 0)])
  File "z3_ir.py", line 26, in check_interp
    l = interp.as_list()
AttributeError: QuantifierRef instance has no attribute 'as_list'

ERROR x86/unit/mn_div.py llvm

ERROR testqemu64.py test-x86_64 test_mul expected_x86_64/test_mul.exp --jitter llvm
[WARNING]: Create dummy entry for 'xxx.dll'

ERROR testqemu64.py test-x86_64 test_rcl expected_x86_64/test_rcl.exp --jitter llvm
[WARNING]: Create dummy entry for 'xxx.dll'

ERROR run_with_linuxenv.py -v -p /(.*lib.*\.so(\.\d+)?)|(/etc/ld.so.*)|(.*magic.*)|(/bin/ls) --jitter llvm /usr/bin/file /bin/ls
[DEBUG]: sys_brk(0)
[DEBUG]: -> 74000000
[DEBUG]: sys_newuname(123faf4)
[DEBUG]: -> 0
[DEBUG]: sys_access(/etc/ld.so.nohwcap, 0)
[DEBUG]: -> ffffffffffffffff
[DEBUG]: sys_access(/etc/ld.so.preload, 4)
[DEBUG]: -> ffffffffffffffff
[DEBUG]: sys_open('/etc/ld.so.cache', 80000, 1)
[DEBUG]: -> 3
[DEBUG]: sys_fstat(3, 123f4c4)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(0, 24796, 1, 2, 3, 0)
[DEBUG]: -> 80027000
[DEBUG]: sys_close(3)
[DEBUG]: -> 0
[DEBUG]: sys_access(/etc/ld.so.nohwcap, 0)
[DEBUG]: -> ffffffffffffffff
[DEBUG]: sys_open('/usr/lib/x86_64-linux-gnu/libmagic.so.1', 80000, 80227168)
[DEBUG]: -> 4
[DEBUG]: sys_read(4, 123f67c, 340)
[DEBUG]: -> 340
[DEBUG]: sys_fstat(4, 123f514)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(0, 21f5a0, 5, 802, 4, 0)
[DEBUG]: -> 80229000
[DEBUG]: sys_mprotect(80247000, 200000, 0)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(80447000, 2000, 3, 812, 4, 1e000)
[DEBUG]: -> 80447000
[DEBUG]: sys_close(4)
[DEBUG]: -> 0
[DEBUG]: sys_access(/etc/ld.so.nohwcap, 0)
[DEBUG]: -> ffffffffffffffff
[DEBUG]: sys_open('/lib/x86_64-linux-gnu/libc.so.6', 80000, 80227168)
[DEBUG]: -> 5
[DEBUG]: sys_read(5, 123f64c, 340)
[DEBUG]: -> 340
[DEBUG]: sys_fstat(5, 123f4e4)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(0, 1000, 3, 22, ffffffffffffffff, 0)
[DEBUG]: -> 8004c000
[DEBUG]: sys_mmap(0, 3c99a0, 5, 802, 5, 0)
[DEBUG]: -> 8044a000
[DEBUG]: sys_mprotect(8060a000, 200000, 0)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(8080a000, 6000, 3, 812, 5, 1c0000)
[DEBUG]: -> 8080a000
[DEBUG]: sys_mmap(80810000, 39a0, 3, 32, ffffffffffffffff, 0)
[DEBUG]: -> 80810000
[DEBUG]: sys_close(5)
[DEBUG]: -> 0
[DEBUG]: sys_access(/etc/ld.so.nohwcap, 0)
[DEBUG]: -> ffffffffffffffff
[DEBUG]: sys_open('/lib/x86_64-linux-gnu/libz.so.1', 80000, 802278e0)
[DEBUG]: -> 6
[DEBUG]: sys_read(6, 123f51c, 340)
[DEBUG]: -> 340
[DEBUG]: sys_fstat(6, 123f3b4)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(0, 219128, 5, 802, 6, 0)
[DEBUG]: -> 80814000
[DEBUG]: sys_mprotect(8082d000, 1ff000, 0)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(80a2c000, 2000, 3, 812, 6, 18000)
[DEBUG]: -> 80a2c000
[DEBUG]: sys_close(6)
[DEBUG]: -> 0
[DEBUG]: sys_mmap(0, 1000, 3, 22, ffffffffffffffff, 0)
[DEBUG]: -> 8004e000
```

**Comment by serpilliere** [comment]
Hi!

For the `mn_div.py` it seems this is linked to a llvm7: can you confirm you have llvm 7 and not llvm6?
For the z3 bugs, same here on archlinux. So I definitively have to look at this

**Comment by serpilliere** [comment]
Ok, I have something for the error:
```
z3.z3types.Z3Exception: True, False or Z3 Boolean expression expected. Received [If(And(Extract(7,
```

It seems that the api `parse_smt2_string` from the z3 package returns a list of objects now, instead of the object itself...

**Comment by commial** [comment]
Regarding the `z3_ir.py` error, we can likely use the `model.eval` API instead of inspecting the AST of z3

**Comment by davidleejy** [comment]
@serpilliere 
Turns out my llvm was quite ancient (llvm version 3.8). This seems to be the version supplied by ubuntu's default repository. Clang was version 3.8 too. 

I removed clang and llvm, installed llvm 7 and clang 7 via llvm's PPA, deleted miasm's `build` dir, re-ran `python setup.py build` and `python setup.py install`. The "arm/arch.py gcc " test passed. But I spotted another test failure.

```
 TEST/ARCH x86/unit/mn_getset128.py python 
ERROR x86/unit/mn_div.py llvm

 TEST/ARCH arm/arch.py gcc 
DONE x86/unit/mn_punpck.py llvm 2s
```

**Comment by serpilliere** [comment]
Thank you for the feedback. I think we can reproduce this one here (but don't have solution yet).
If you fall on a binary which uses this, maybe you will have to emulate it with the gcc jitter of miasm for the moment.

**Comment by serpilliere** [comment]
Thank you for the feedback. I think we can reproduce this one here (but don't have solution yet).
If you come across a binary which uses this, maybe you will have to emulate it with the gcc jitter of miasm for the moment.

**Comment by davidleejy** [comment]
I was trying to install Miasm as I was going to use Sybil (https://github.com/cea-sec/Sibyl). Advise, if convenient, would be appreciated.

Thank you & @commial for replying. Now I have a hint as to what may have caused the errors.

**Comment by serpilliere** [comment]
If you are using the gcc jitter (or even qemu for sybil), I think these bugs won't be visible for you.

**Comment by davidleejy** [comment]
I see! Appreciate the advise

**Comment by serpilliere** [comment]
I am linking this one to the reported bug in ollvm:
numba/llvmlite#495
